--[[
-- My Neovim
--]]
require("NvimPy.Lazy")
require("NvimPy.lsp")
require("NvimPy.Lsp-colors")
require("NvimPy.Cmp")
require("NvimPy.Options")
require("NvimPy.TS")
require("NvimPy.Clip")
require("NvimPy.Search")
require("NvimPy.Keymaps")
require("NvimPy.Tree")
require("NvimPy.Symbols")
require("NvimPy.Lualine")
vim.cmd([[colorscheme nightfly]])
require("NvimPy.Cursor")
require("NvimPy.Alpha")
require("NvimPy.Noice")
require("NvimPy.Brackets")
require("NvimPy.Pairs")
require("NvimPy.Indent")
require("NvimPy.Winsep")
require("NvimPy.Knap")
require("NvimPy.Winbar")
require("NvimPy.BarBar")
require("NvimPy.Autocmds")
require("colorizer").setup()
require("toggleterm").setup()
require("window-picker").setup()


require("luasnip.loaders.from_vscode").lazy_load()
require("luasnip.loaders.from_lua").load({paths = "~/.config/nvim/Snippets/"})
