return {
	-- {
	-- 	"supermaven-inc/supermaven-nvim",
	-- 	build = ":SupermavenUseFree",
	-- 	event = { "VeryLazy", "InsertEnter" },
	-- 	config = function()
	-- 		require("supermaven-nvim.completion_preview").suggestion_group = "NonText"
	-- 		require("supermaven-nvim").setup({
	-- 			keymaps = {
	-- 				accept_suggestion = "<A-Tab>",
	-- 				clear_suggestion = "<C-]>",
	-- 				accept_word = "<C-j>",
	-- 			},
	-- 			ignore_filetypes = {
	-- 				cpp = true,
	-- 				gitcommit = true,
	-- 				DressingInput = true,
	-- 				TelescopePrompt = true,
	-- 				text = true, -- `pass`' filetype when editing passwords
	-- 				["rip-substitute"] = true,
	-- 			},
	-- 			color = {
	-- 				suggestion_color = "#acafac",
	-- 				cterm = 244,
	-- 			},
	-- 			log_level = "info", -- set to "off" to disable logging completely
	-- 			disable_inline_completion = false, -- disables inline completion for use with cmp
	-- 			disable_keymaps = false, -- disables built in keymaps for more manual control})
	-- 		})
	-- 	end,
	-- },
}
