return {
	{ symbol = "¡", digraph = "!I", name = "INVERTED EXCLAMATION MARK" },
	{ symbol = "¢", digraph = "Ct", name = "CENT SIGN" },
	{ symbol = "£", digraph = "Pd", name = "POUND SIGN" },
	{ symbol = "¤", digraph = "Cu", name = "CURRENCY SIGN" },
	{ symbol = "¥", digraph = "Ye", name = "YEN SIGN" },
	{ symbol = "¦", digraph = "BB", name = "BROKEN BAR" },
	{ symbol = "§", digraph = "SE", name = "SECTION SIGN" },
	{ symbol = "¨", digraph = "':", name = "DIAERESIS" },
	{ symbol = "©", digraph = "Co", name = "COPYRIGHT SIGN" },
	{ symbol = "ª", digraph = "-a", name = "FEMININE ORDINAL INDICATOR" },
	{ symbol = "«", digraph = "<<", name = "LEFT-POINTING DOUBLE ANGLE QUOTATION MARK" },
	{ symbol = "¬", digraph = "NO", name = "NOT SIGN" },
	{ symbol = "­", digraph = "--", name = "SOFT HYPHEN" },
	{ symbol = "®", digraph = "Rg", name = "REGISTERED SIGN" },
	{ symbol = "¯", digraph = "'m", name = "MACRON" },
	{ symbol = "°", digraph = "DG", name = "DEGREE SIGN" },
	{ symbol = "±", digraph = "+-", name = "PLUS-MINUS SIGN" },
	{ symbol = "²", digraph = "2S", name = "SUPERSCRIPT TWO" },
	{ symbol = "³", digraph = "3S", name = "SUPERSCRIPT THREE" },
	{ symbol = "´", digraph = "''", name = "ACUTE ACCENT" },
	{ symbol = "µ", digraph = "My", name = "MICRO SIGN" },
	{ symbol = "¶", digraph = "PI", name = "PILCROW SIGN" },
	{ symbol = "·", digraph = ".M", name = "MIDDLE DOT" },
	{ symbol = "¸", digraph = "',", name = "CEDILLA" },
	{ symbol = "¹", digraph = "1S", name = "SUPERSCRIPT ONE" },
	{ symbol = "º", digraph = "-o", name = "MASCULINE ORDINAL INDICATOR" },
	{ symbol = "»", digraph = ">>", name = "RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK" },
	{ symbol = "¼", digraph = "14", name = "VULGAR FRACTION ONE QUARTER" },
	{ symbol = "½", digraph = "12", name = "VULGAR FRACTION ONE HALF" },
	{ symbol = "¾", digraph = "34", name = "VULGAR FRACTION THREE QUARTERS" },
	{ symbol = "¿", digraph = "?I", name = "INVERTED QUESTION MARK" },
	{ symbol = "À", digraph = "A!", name = "LATIN CAPITAL LETTER A WITH GRAVE" },
	{ symbol = "Á", digraph = "A'", name = "LATIN CAPITAL LETTER A WITH ACUTE" },
	{ symbol = "Â", digraph = "A>", name = "LATIN CAPITAL LETTER A WITH CIRCUMFLEX" },
	{ symbol = "Ã", digraph = "A?", name = "LATIN CAPITAL LETTER A WITH TILDE" },
	{ symbol = "Ä", digraph = "A:", name = "LATIN CAPITAL LETTER A WITH DIAERESIS" },
	{ symbol = "Å", digraph = "AA", name = "LATIN CAPITAL LETTER A WITH RING ABOVE" },
	{ symbol = "Æ", digraph = "AE", name = "LATIN CAPITAL LETTER AE" },
	{ symbol = "Ç", digraph = "C,", name = "LATIN CAPITAL LETTER C WITH CEDILLA" },
	{ symbol = "È", digraph = "E!", name = "LATIN CAPITAL LETTER E WITH GRAVE" },
	{ symbol = "É", digraph = "E'", name = "LATIN CAPITAL LETTER E WITH ACUTE" },
	{ symbol = "Ê", digraph = "E>", name = "LATIN CAPITAL LETTER E WITH CIRCUMFLEX" },
	{ symbol = "Ë", digraph = "E:", name = "LATIN CAPITAL LETTER E WITH DIAERESIS" },
	{ symbol = "Ì", digraph = "I!", name = "LATIN CAPITAL LETTER I WITH GRAVE" },
	{ symbol = "Í", digraph = "I'", name = "LATIN CAPITAL LETTER I WITH ACUTE" },
	{ symbol = "Î", digraph = "I>", name = "LATIN CAPITAL LETTER I WITH CIRCUMFLEX" },
	{ symbol = "Ï", digraph = "I:", name = "LATIN CAPITAL LETTER I WITH DIAERESIS" },
	{ symbol = "Ð", digraph = "D-", name = "LATIN CAPITAL LETTER ETH (Icelandic)" },
	{ symbol = "Ñ", digraph = "N?", name = "LATIN CAPITAL LETTER N WITH TILDE" },
	{ symbol = "Ò", digraph = "O!", name = "LATIN CAPITAL LETTER O WITH GRAVE" },
	{ symbol = "Ó", digraph = "O'", name = "LATIN CAPITAL LETTER O WITH ACUTE" },
	{ symbol = "Ô", digraph = "O>", name = "LATIN CAPITAL LETTER O WITH CIRCUMFLEX" },
	{ symbol = "Õ", digraph = "O?", name = "LATIN CAPITAL LETTER O WITH TILDE" },
	{ symbol = "Ö", digraph = "O:", name = "LATIN CAPITAL LETTER O WITH DIAERESIS" },
	{ symbol = "×", digraph = "*X", name = "MULTIPLICATION SIGN" },
	{ symbol = "Ø", digraph = "O/", name = "LATIN CAPITAL LETTER O WITH STROKE" },
	{ symbol = "Ù", digraph = "U!", name = "LATIN CAPITAL LETTER U WITH GRAVE" },
	{ symbol = "Ú", digraph = "U'", name = "LATIN CAPITAL LETTER U WITH ACUTE" },
	{ symbol = "Û", digraph = "U>", name = "LATIN CAPITAL LETTER U WITH CIRCUMFLEX" },
	{ symbol = "Ü", digraph = "U:", name = "LATIN CAPITAL LETTER U WITH DIAERESIS" },
	{ symbol = "Ý", digraph = "Y'", name = "LATIN CAPITAL LETTER Y WITH ACUTE" },
	{ symbol = "Þ", digraph = "TH", name = "LATIN CAPITAL LETTER THORN (Icelandic)" },
	{ symbol = "ß", digraph = "ss", name = "LATIN SMALL LETTER SHARP S (German)" },
	{ symbol = "à", digraph = "a!", name = "LATIN SMALL LETTER A WITH GRAVE" },
	{ symbol = "á", digraph = "a'", name = "LATIN SMALL LETTER A WITH ACUTE" },
	{ symbol = "â", digraph = "a>", name = "LATIN SMALL LETTER A WITH CIRCUMFLEX" },
	{ symbol = "ã", digraph = "a?", name = "LATIN SMALL LETTER A WITH TILDE" },
	{ symbol = "ä", digraph = "a:", name = "LATIN SMALL LETTER A WITH DIAERESIS" },
	{ symbol = "å", digraph = "aa", name = "LATIN SMALL LETTER A WITH RING ABOVE" },
	{ symbol = "æ", digraph = "ae", name = "LATIN SMALL LETTER AE" },
	{ symbol = "ç", digraph = "c,", name = "LATIN SMALL LETTER C WITH CEDILLA" },
	{ symbol = "è", digraph = "e!", name = "LATIN SMALL LETTER E WITH GRAVE" },
	{ symbol = "é", digraph = "e'", name = "LATIN SMALL LETTER E WITH ACUTE" },
	{ symbol = "ê", digraph = "e>", name = "LATIN SMALL LETTER E WITH CIRCUMFLEX" },
	{ symbol = "ë", digraph = "e:", name = "LATIN SMALL LETTER E WITH DIAERESIS" },
	{ symbol = "ì", digraph = "i!", name = "LATIN SMALL LETTER I WITH GRAVE" },
	{ symbol = "í", digraph = "i'", name = "LATIN SMALL LETTER I WITH ACUTE" },
	{ symbol = "î", digraph = "i>", name = "LATIN SMALL LETTER I WITH CIRCUMFLEX" },
	{ symbol = "ï", digraph = "i:", name = "LATIN SMALL LETTER I WITH DIAERESIS" },
	{ symbol = "ð", digraph = "d-", name = "LATIN SMALL LETTER ETH (Icelandic)" },
	{ symbol = "ñ", digraph = "n?", name = "LATIN SMALL LETTER N WITH TILDE" },
	{ symbol = "ò", digraph = "o!", name = "LATIN SMALL LETTER O WITH GRAVE" },
	{ symbol = "ó", digraph = "o'", name = "LATIN SMALL LETTER O WITH ACUTE" },
	{ symbol = "ô", digraph = "o>", name = "LATIN SMALL LETTER O WITH CIRCUMFLEX" },
	{ symbol = "õ", digraph = "o?", name = "LATIN SMALL LETTER O WITH TILDE" },
	{ symbol = "ö", digraph = "o:", name = "LATIN SMALL LETTER O WITH DIAERESIS" },
	{ symbol = "÷", digraph = "-:", name = "DIVISION SIGN" },
	{ symbol = "ø", digraph = "o/", name = "LATIN SMALL LETTER O WITH STROKE" },
	{ symbol = "ù", digraph = "u!", name = "LATIN SMALL LETTER U WITH GRAVE" },
	{ symbol = "ú", digraph = "u'", name = "LATIN SMALL LETTER U WITH ACUTE" },
	{ symbol = "û", digraph = "u>", name = "LATIN SMALL LETTER U WITH CIRCUMFLEX" },
	{ symbol = "ü", digraph = "u:", name = "LATIN SMALL LETTER U WITH DIAERESIS" },
	{ symbol = "ý", digraph = "y'", name = "LATIN SMALL LETTER Y WITH ACUTE" },
	{ symbol = "þ", digraph = "th", name = "LATIN SMALL LETTER THORN (Icelandic)" },
	{ symbol = "ÿ", digraph = "y:", name = "LATIN SMALL LETTER Y WITH DIAERESIS" },
	{ symbol = "Ā", digraph = "A-", name = "LATIN CAPITAL LETTER A WITH MACRON" },
	{ symbol = "ā", digraph = "a-", name = "LATIN SMALL LETTER A WITH MACRON" },
	{ symbol = "Ă", digraph = "A(", name = "LATIN CAPITAL LETTER A WITH BREVE" },
	{ symbol = "ă", digraph = "a(", name = "LATIN SMALL LETTER A WITH BREVE" },
	{ symbol = "Ą", digraph = "A;", name = "LATIN CAPITAL LETTER A WITH OGONEK" },
	{ symbol = "ą", digraph = "a;", name = "LATIN SMALL LETTER A WITH OGONEK" },
	{ symbol = "Ć", digraph = "C'", name = "LATIN CAPITAL LETTER C WITH ACUTE" },
	{ symbol = "ć", digraph = "c'", name = "LATIN SMALL LETTER C WITH ACUTE" },
	{ symbol = "Ĉ", digraph = "C>", name = "LATIN CAPITAL LETTER C WITH CIRCUMFLEX" },
	{ symbol = "ĉ", digraph = "c>", name = "LATIN SMALL LETTER C WITH CIRCUMFLEX" },
	{ symbol = "Ċ", digraph = "C.", name = "LATIN CAPITAL LETTER C WITH DOT ABOVE" },
	{ symbol = "ċ", digraph = "c.", name = "LATIN SMALL LETTER C WITH DOT ABOVE" },
	{ symbol = "Č", digraph = "C<", name = "LATIN CAPITAL LETTER C WITH CARON" },
	{ symbol = "č", digraph = "c<", name = "LATIN SMALL LETTER C WITH CARON" },
	{ symbol = "Ď", digraph = "D<", name = "LATIN CAPITAL LETTER D WITH CARON" },
	{ symbol = "ď", digraph = "d<", name = "LATIN SMALL LETTER D WITH CARON" },
	{ symbol = "Đ", digraph = "D/", name = "LATIN CAPITAL LETTER D WITH STROKE" },
	{ symbol = "đ", digraph = "d/", name = "LATIN SMALL LETTER D WITH STROKE" },
	{ symbol = "Ē", digraph = "E-", name = "LATIN CAPITAL LETTER E WITH MACRON" },
	{ symbol = "ē", digraph = "e-", name = "LATIN SMALL LETTER E WITH MACRON" },
	{ symbol = "Ĕ", digraph = "E(", name = "LATIN CAPITAL LETTER E WITH BREVE" },
	{ symbol = "ĕ", digraph = "e(", name = "LATIN SMALL LETTER E WITH BREVE" },
	{ symbol = "Ė", digraph = "E.", name = "LATIN CAPITAL LETTER E WITH DOT ABOVE" },
	{ symbol = "ė", digraph = "e.", name = "LATIN SMALL LETTER E WITH DOT ABOVE" },
	{ symbol = "Ę", digraph = "E;", name = "LATIN CAPITAL LETTER E WITH OGONEK" },
	{ symbol = "ę", digraph = "e;", name = "LATIN SMALL LETTER E WITH OGONEK" },
	{ symbol = "Ě", digraph = "E<", name = "LATIN CAPITAL LETTER E WITH CARON" },
	{ symbol = "ě", digraph = "e<", name = "LATIN SMALL LETTER E WITH CARON" },
	{ symbol = "Ĝ", digraph = "G>", name = "LATIN CAPITAL LETTER G WITH CIRCUMFLEX" },
	{ symbol = "ĝ", digraph = "g>", name = "LATIN SMALL LETTER G WITH CIRCUMFLEX" },
	{ symbol = "Ğ", digraph = "G(", name = "LATIN CAPITAL LETTER G WITH BREVE" },
	{ symbol = "ğ", digraph = "g(", name = "LATIN SMALL LETTER G WITH BREVE" },
	{ symbol = "Ġ", digraph = "G.", name = "LATIN CAPITAL LETTER G WITH DOT ABOVE" },
	{ symbol = "ġ", digraph = "g.", name = "LATIN SMALL LETTER G WITH DOT ABOVE" },
	{ symbol = "Ģ", digraph = "G,", name = "LATIN CAPITAL LETTER G WITH CEDILLA" },
	{ symbol = "ģ", digraph = "g,", name = "LATIN SMALL LETTER G WITH CEDILLA" },
	{ symbol = "Ĥ", digraph = "H>", name = "LATIN CAPITAL LETTER H WITH CIRCUMFLEX" },
	{ symbol = "ĥ", digraph = "h>", name = "LATIN SMALL LETTER H WITH CIRCUMFLEX" },
	{ symbol = "Ħ", digraph = "H/", name = "LATIN CAPITAL LETTER H WITH STROKE" },
	{ symbol = "ħ", digraph = "h/", name = "LATIN SMALL LETTER H WITH STROKE" },
	{ symbol = "Ĩ", digraph = "I?", name = "LATIN CAPITAL LETTER I WITH TILDE" },
	{ symbol = "ĩ", digraph = "i?", name = "LATIN SMALL LETTER I WITH TILDE" },
	{ symbol = "Ī", digraph = "I-", name = "LATIN CAPITAL LETTER I WITH MACRON" },
	{ symbol = "ī", digraph = "i-", name = "LATIN SMALL LETTER I WITH MACRON" },
	{ symbol = "Ĭ", digraph = "I(", name = "LATIN CAPITAL LETTER I WITH BREVE" },
	{ symbol = "ĭ", digraph = "i(", name = "LATIN SMALL LETTER I WITH BREVE" },
	{ symbol = "Į", digraph = "I;", name = "LATIN CAPITAL LETTER I WITH OGONEK" },
	{ symbol = "į", digraph = "i;", name = "LATIN SMALL LETTER I WITH OGONEK" },
	{ symbol = "İ", digraph = "I.", name = "LATIN CAPITAL LETTER I WITH DOT ABOVE" },
	{ symbol = "ı", digraph = "i.", name = "LATIN SMALL LETTER DOTLESS I" },
	{ symbol = "Ĳ", digraph = "IJ", name = "LATIN CAPITAL LIGATURE IJ" },
	{ symbol = "ĳ", digraph = "ij", name = "LATIN SMALL LIGATURE IJ" },
	{ symbol = "Ĵ", digraph = "J>", name = "LATIN CAPITAL LETTER J WITH CIRCUMFLEX" },
	{ symbol = "ĵ", digraph = "j>", name = "LATIN SMALL LETTER J WITH CIRCUMFLEX" },
	{ symbol = "Ķ", digraph = "K,", name = "LATIN CAPITAL LETTER K WITH CEDILLA" },
	{ symbol = "ķ", digraph = "k,", name = "LATIN SMALL LETTER K WITH CEDILLA" },
	{ symbol = "ĸ", digraph = "kk", name = "LATIN SMALL LETTER KRA" },
	{ symbol = "Ĺ", digraph = "L'", name = "LATIN CAPITAL LETTER L WITH ACUTE" },
	{ symbol = "ĺ", digraph = "l'", name = "LATIN SMALL LETTER L WITH ACUTE" },
	{ symbol = "Ļ", digraph = "L,", name = "LATIN CAPITAL LETTER L WITH CEDILLA" },
	{ symbol = "ļ", digraph = "l,", name = "LATIN SMALL LETTER L WITH CEDILLA" },
	{ symbol = "Ľ", digraph = "L<", name = "LATIN CAPITAL LETTER L WITH CARON" },
	{ symbol = "ľ", digraph = "l<", name = "LATIN SMALL LETTER L WITH CARON" },
	{ symbol = "Ŀ", digraph = "L.", name = "LATIN CAPITAL LETTER L WITH MIDDLE DOT" },
	{ symbol = "ŀ", digraph = "l.", name = "LATIN SMALL LETTER L WITH MIDDLE DOT" },
	{ symbol = "Ł", digraph = "L/", name = "LATIN CAPITAL LETTER L WITH STROKE" },
	{ symbol = "ł", digraph = "l/", name = "LATIN SMALL LETTER L WITH STROKE" },
	{ symbol = "Ń", digraph = "N'", name = "LATIN CAPITAL LETTER N WITH ACUTE `" },
	{ symbol = "ń", digraph = "n'", name = "LATIN SMALL LETTER N WITH ACUTE `" },
	{ symbol = "Ņ", digraph = "N,", name = "LATIN CAPITAL LETTER N WITH CEDILLA `" },
	{ symbol = "ņ", digraph = "n,", name = "LATIN SMALL LETTER N WITH CEDILLA `" },
	{ symbol = "Ň", digraph = "N<", name = "LATIN CAPITAL LETTER N WITH CARON `" },
	{ symbol = "ň", digraph = "n<", name = "LATIN SMALL LETTER N WITH CARON `" },
	{ symbol = "ŉ", digraph = "'n", name = "LATIN SMALL LETTER N PRECEDED BY APOSTROPHE `" },
	{ symbol = "Ŋ", digraph = "NG", name = "LATIN CAPITAL LETTER ENG" },
	{ symbol = "ŋ", digraph = "ng", name = "LATIN SMALL LETTER ENG" },
	{ symbol = "Ō", digraph = "O-", name = "LATIN CAPITAL LETTER O WITH MACRON" },
	{ symbol = "ō", digraph = "o-", name = "LATIN SMALL LETTER O WITH MACRON" },
	{ symbol = "Ŏ", digraph = "O(", name = "LATIN CAPITAL LETTER O WITH BREVE" },
	{ symbol = "ŏ", digraph = "o(", name = "LATIN SMALL LETTER O WITH BREVE" },
	{ symbol = "Ő", digraph = 'O"', name = "LATIN CAPITAL LETTER O WITH DOUBLE ACUTE" },
	{ symbol = "ő", digraph = 'o"', name = "LATIN SMALL LETTER O WITH DOUBLE ACUTE" },
	{ symbol = "Œ", digraph = "OE", name = "LATIN CAPITAL LIGATURE OE" },
	{ symbol = "œ", digraph = "oe", name = "LATIN SMALL LIGATURE OE" },
	{ symbol = "Ŕ", digraph = "R'", name = "LATIN CAPITAL LETTER R WITH ACUTE" },
	{ symbol = "ŕ", digraph = "r'", name = "LATIN SMALL LETTER R WITH ACUTE" },
	{ symbol = "Ŗ", digraph = "R,", name = "LATIN CAPITAL LETTER R WITH CEDILLA" },
	{ symbol = "ŗ", digraph = "r,", name = "LATIN SMALL LETTER R WITH CEDILLA" },
	{ symbol = "Ř", digraph = "R<", name = "LATIN CAPITAL LETTER R WITH CARON" },
	{ symbol = "ř", digraph = "r<", name = "LATIN SMALL LETTER R WITH CARON" },
	{ symbol = "Ś", digraph = "S'", name = "LATIN CAPITAL LETTER S WITH ACUTE" },
	{ symbol = "ś", digraph = "s'", name = "LATIN SMALL LETTER S WITH ACUTE" },
	{ symbol = "Ŝ", digraph = "S>", name = "LATIN CAPITAL LETTER S WITH CIRCUMFLEX" },
	{ symbol = "ŝ", digraph = "s>", name = "LATIN SMALL LETTER S WITH CIRCUMFLEX" },
	{ symbol = "Ş", digraph = "S,", name = "LATIN CAPITAL LETTER S WITH CEDILLA" },
	{ symbol = "ş", digraph = "s,", name = "LATIN SMALL LETTER S WITH CEDILLA" },
	{ symbol = "Š", digraph = "S<", name = "LATIN CAPITAL LETTER S WITH CARON" },
	{ symbol = "š", digraph = "s<", name = "LATIN SMALL LETTER S WITH CARON" },
	{ symbol = "Ţ", digraph = "T,", name = "LATIN CAPITAL LETTER T WITH CEDILLA" },
	{ symbol = "ţ", digraph = "t,", name = "LATIN SMALL LETTER T WITH CEDILLA" },
	{ symbol = "Ť", digraph = "T<", name = "LATIN CAPITAL LETTER T WITH CARON" },
	{ symbol = "ť", digraph = "t<", name = "LATIN SMALL LETTER T WITH CARON" },
	{ symbol = "Ŧ", digraph = "T/", name = "LATIN CAPITAL LETTER T WITH STROKE" },
	{ symbol = "ŧ", digraph = "t/", name = "LATIN SMALL LETTER T WITH STROKE" },
	{ symbol = "Ũ", digraph = "U?", name = "LATIN CAPITAL LETTER U WITH TILDE" },
	{ symbol = "ũ", digraph = "u?", name = "LATIN SMALL LETTER U WITH TILDE" },
	{ symbol = "Ū", digraph = "U-", name = "LATIN CAPITAL LETTER U WITH MACRON" },
	{ symbol = "ū", digraph = "u-", name = "LATIN SMALL LETTER U WITH MACRON" },
	{ symbol = "Ŭ", digraph = "U(", name = "LATIN CAPITAL LETTER U WITH BREVE" },
	{ symbol = "ŭ", digraph = "u(", name = "LATIN SMALL LETTER U WITH BREVE" },
	{ symbol = "Ů", digraph = "U0", name = "LATIN CAPITAL LETTER U WITH RING ABOVE" },
	{ symbol = "ů", digraph = "u0", name = "LATIN SMALL LETTER U WITH RING ABOVE" },
	{ symbol = "Ű", digraph = 'U"', name = "LATIN CAPITAL LETTER U WITH DOUBLE ACUTE" },
	{ symbol = "ű", digraph = 'u"', name = "LATIN SMALL LETTER U WITH DOUBLE ACUTE" },
	{ symbol = "Ų", digraph = "U;", name = "LATIN CAPITAL LETTER U WITH OGONEK" },
	{ symbol = "ų", digraph = "u;", name = "LATIN SMALL LETTER U WITH OGONEK" },
	{ symbol = "Ŵ", digraph = "W>", name = "LATIN CAPITAL LETTER W WITH CIRCUMFLEX" },
	{ symbol = "ŵ", digraph = "w>", name = "LATIN SMALL LETTER W WITH CIRCUMFLEX" },
	{ symbol = "Ŷ", digraph = "Y>", name = "LATIN CAPITAL LETTER Y WITH CIRCUMFLEX" },
	{ symbol = "ŷ", digraph = "y>", name = "LATIN SMALL LETTER Y WITH CIRCUMFLEX" },
	{ symbol = "Ÿ", digraph = "Y:", name = "LATIN CAPITAL LETTER Y WITH DIAERESIS" },
	{ symbol = "Ź", digraph = "Z'", name = "LATIN CAPITAL LETTER Z WITH ACUTE" },
	{ symbol = "ź", digraph = "z'", name = "LATIN SMALL LETTER Z WITH ACUTE" },
	{ symbol = "Ż", digraph = "Z.", name = "LATIN CAPITAL LETTER Z WITH DOT ABOVE" },
	{ symbol = "ż", digraph = "z.", name = "LATIN SMALL LETTER Z WITH DOT ABOVE" },
	{ symbol = "Ž", digraph = "Z<", name = "LATIN CAPITAL LETTER Z WITH CARON" },
	{ symbol = "ž", digraph = "z<", name = "LATIN SMALL LETTER Z WITH CARON" },
	{ symbol = "Ơ", digraph = "O9", name = "LATIN CAPITAL LETTER O WITH HORN" },
	{ symbol = "ơ", digraph = "o9", name = "LATIN SMALL LETTER O WITH HORN" },
	{ symbol = "Ƣ", digraph = "OI", name = "LATIN CAPITAL LETTER OI" },
	{ symbol = "ƣ", digraph = "oi", name = "LATIN SMALL LETTER OI" },
	{ symbol = "Ʀ", digraph = "yr", name = "LATIN LETTER YR" },
	{ symbol = "Ư", digraph = "U9", name = "LATIN CAPITAL LETTER U WITH HORN" },
	{ symbol = "ư", digraph = "u9", name = "LATIN SMALL LETTER U WITH HORN" },
	{ symbol = "Ƶ", digraph = "Z/", name = "LATIN CAPITAL LETTER Z WITH STROKE" },
	{ symbol = "ƶ", digraph = "z/", name = "LATIN SMALL LETTER Z WITH STROKE" },
	{ symbol = "Ʒ", digraph = "ED", name = "LATIN CAPITAL LETTER EZH" },
	{ symbol = "Ǎ", digraph = "A<", name = "LATIN CAPITAL LETTER A WITH CARON" },
	{ symbol = "ǎ", digraph = "a<", name = "LATIN SMALL LETTER A WITH CARON" },
	{ symbol = "Ǐ", digraph = "I<", name = "LATIN CAPITAL LETTER I WITH CARON" },
	{ symbol = "ǐ", digraph = "i<", name = "LATIN SMALL LETTER I WITH CARON" },
	{ symbol = "Ǒ", digraph = "O<", name = "LATIN CAPITAL LETTER O WITH CARON" },
	{ symbol = "ǒ", digraph = "o<", name = "LATIN SMALL LETTER O WITH CARON" },
	{ symbol = "Ǔ", digraph = "U<", name = "LATIN CAPITAL LETTER U WITH CARON" },
	{ symbol = "ǔ", digraph = "u<", name = "LATIN SMALL LETTER U WITH CARON" },
	{ symbol = "Ǟ", digraph = "A1", name = "LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON" },
	{ symbol = "ǟ", digraph = "a1", name = "LATIN SMALL LETTER A WITH DIAERESIS AND MACRON" },
	{ symbol = "Ǡ", digraph = "A7", name = "LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON" },
	{ symbol = "ǡ", digraph = "a7", name = "LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON" },
	{ symbol = "Ǣ", digraph = "A3", name = "LATIN CAPITAL LETTER AE WITH MACRON" },
	{ symbol = "ǣ", digraph = "a3", name = "LATIN SMALL LETTER AE WITH MACRON" },
	{ symbol = "Ǥ", digraph = "G/", name = "LATIN CAPITAL LETTER G WITH STROKE" },
	{ symbol = "ǥ", digraph = "g/", name = "LATIN SMALL LETTER G WITH STROKE" },
	{ symbol = "Ǧ", digraph = "G<", name = "LATIN CAPITAL LETTER G WITH CARON" },
	{ symbol = "ǧ", digraph = "g<", name = "LATIN SMALL LETTER G WITH CARON" },
	{ symbol = "Ǩ", digraph = "K<", name = "LATIN CAPITAL LETTER K WITH CARON" },
	{ symbol = "ǩ", digraph = "k<", name = "LATIN SMALL LETTER K WITH CARON" },
	{ symbol = "Ǫ", digraph = "O;", name = "LATIN CAPITAL LETTER O WITH OGONEK" },
	{ symbol = "ǫ", digraph = "o;", name = "LATIN SMALL LETTER O WITH OGONEK" },
	{ symbol = "Ǭ", digraph = "O1", name = "LATIN CAPITAL LETTER O WITH OGONEK AND MACRON" },
	{ symbol = "ǭ", digraph = "o1", name = "LATIN SMALL LETTER O WITH OGONEK AND MACRON" },
	{ symbol = "Ǯ", digraph = "EZ", name = "LATIN CAPITAL LETTER EZH WITH CARON" },
	{ symbol = "ǯ", digraph = "ez", name = "LATIN SMALL LETTER EZH WITH CARON" },
	{ symbol = "ǰ", digraph = "j<", name = "LATIN SMALL LETTER J WITH CARON" },
	{ symbol = "Ǵ", digraph = "G'", name = "LATIN CAPITAL LETTER G WITH ACUTE" },
	{ symbol = "ǵ", digraph = "g'", name = "LATIN SMALL LETTER G WITH ACUTE" },
	{ symbol = "ʿ", digraph = ";S", name = "MODIFIER LETTER LEFT HALF RING" },
	{ symbol = "ˇ", digraph = "'<", name = "CARON" },
	{ symbol = "˘", digraph = "'(", name = "BREVE" },
	{ symbol = "˙", digraph = "'.", name = "DOT ABOVE" },
	{ symbol = "˚", digraph = "'0", name = "RING ABOVE" },
	{ symbol = "˛", digraph = "';", name = "OGONEK" },
	{ symbol = "˝", digraph = "'\"", name = "DOUBLE ACUTE ACCENT" },
	{ symbol = "Ά", digraph = "A%", name = "GREEK CAPITAL LETTER ALPHA WITH TONOS" },
	{ symbol = "Έ", digraph = "E%", name = "GREEK CAPITAL LETTER EPSILON WITH TONOS" },
	{ symbol = "Ή", digraph = "Y%", name = "GREEK CAPITAL LETTER ETA WITH TONOS" },
	{ symbol = "Ί", digraph = "I%", name = "GREEK CAPITAL LETTER IOTA WITH TONOS" },
	{ symbol = "Ό", digraph = "O%", name = "GREEK CAPITAL LETTER OMICRON WITH TONOS" },
	{ symbol = "Ύ", digraph = "U%", name = "GREEK CAPITAL LETTER UPSILON WITH TONOS" },
	{ symbol = "Ώ", digraph = "W%", name = "GREEK CAPITAL LETTER OMEGA WITH TONOS" },
	{ symbol = "ΐ", digraph = "i3", name = "GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS" },
	{ symbol = "Α", digraph = "A*", name = "GREEK CAPITAL LETTER ALPHA" },
	{ symbol = "Β", digraph = "B*", name = "GREEK CAPITAL LETTER BETA" },
	{ symbol = "Γ", digraph = "G*", name = "GREEK CAPITAL LETTER GAMMA" },
	{ symbol = "Δ", digraph = "D*", name = "GREEK CAPITAL LETTER DELTA" },
	{ symbol = "Ε", digraph = "E*", name = "GREEK CAPITAL LETTER EPSILON" },
	{ symbol = "Ζ", digraph = "Z*", name = "GREEK CAPITAL LETTER ZETA" },
	{ symbol = "Η", digraph = "Y*", name = "GREEK CAPITAL LETTER ETA" },
	{ symbol = "Θ", digraph = "H*", name = "GREEK CAPITAL LETTER THETA" },
	{ symbol = "Ι", digraph = "I*", name = "GREEK CAPITAL LETTER IOTA" },
	{ symbol = "Κ", digraph = "K*", name = "GREEK CAPITAL LETTER KAPPA" },
	{ symbol = "Λ", digraph = "L*", name = "GREEK CAPITAL LETTER LAMDA (aka LAMBDA)" },
	{ symbol = "Μ", digraph = "M*", name = "GREEK CAPITAL LETTER MU" },
	{ symbol = "Ν", digraph = "N*", name = "GREEK CAPITAL LETTER NU" },
	{ symbol = "Ξ", digraph = "C*", name = "GREEK CAPITAL LETTER XI" },
	{ symbol = "Ο", digraph = "O*", name = "GREEK CAPITAL LETTER OMICRON" },
	{ symbol = "Π", digraph = "P*", name = "GREEK CAPITAL LETTER PI" },
	{ symbol = "Ρ", digraph = "R*", name = "GREEK CAPITAL LETTER RHO" },
	{ symbol = "Σ", digraph = "S*", name = "GREEK CAPITAL LETTER SIGMA" },
	{ symbol = "Τ", digraph = "T*", name = "GREEK CAPITAL LETTER TAU" },
	{ symbol = "Υ", digraph = "U*", name = "GREEK CAPITAL LETTER UPSILON" },
	{ symbol = "Φ", digraph = "F*", name = "GREEK CAPITAL LETTER PHI" },
	{ symbol = "Χ", digraph = "X*", name = "GREEK CAPITAL LETTER CHI" },
	{ symbol = "Ψ", digraph = "Q*", name = "GREEK CAPITAL LETTER PSI" },
	{ symbol = "Ω", digraph = "W*", name = "GREEK CAPITAL LETTER OMEGA" },
	{ symbol = "Ϊ", digraph = "J*", name = "GREEK CAPITAL LETTER IOTA WITH DIALYTIKA" },
	{ symbol = "Ϋ", digraph = "V*", name = "GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA" },
	{ symbol = "ά", digraph = "a%", name = "GREEK SMALL LETTER ALPHA WITH TONOS" },
	{ symbol = "έ", digraph = "e%", name = "GREEK SMALL LETTER EPSILON WITH TONOS" },
	{ symbol = "ή", digraph = "y%", name = "GREEK SMALL LETTER ETA WITH TONOS" },
	{ symbol = "ί", digraph = "i%", name = "GREEK SMALL LETTER IOTA WITH TONOS" },
	{ symbol = "ΰ", digraph = "u3", name = "GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS" },
	{ symbol = "α", digraph = "a*", name = "GREEK SMALL LETTER ALPHA" },
	{ symbol = "β", digraph = "b*", name = "GREEK SMALL LETTER BETA" },
	{ symbol = "γ", digraph = "g*", name = "GREEK SMALL LETTER GAMMA" },
	{ symbol = "δ", digraph = "d*", name = "GREEK SMALL LETTER DELTA" },
	{ symbol = "ε", digraph = "e*", name = "GREEK SMALL LETTER EPSILON" },
	{ symbol = "ζ", digraph = "z*", name = "GREEK SMALL LETTER ZETA" },
	{ symbol = "η", digraph = "y*", name = "GREEK SMALL LETTER ETA" },
	{ symbol = "θ", digraph = "h*", name = "GREEK SMALL LETTER THETA" },
	{ symbol = "ι", digraph = "i*", name = "GREEK SMALL LETTER IOTA" },
	{ symbol = "κ", digraph = "k*", name = "GREEK SMALL LETTER KAPPA" },
	{ symbol = "λ", digraph = "l*", name = "GREEK SMALL LETTER LAMDA (aka LAMBDA)" },
	{ symbol = "μ", digraph = "m*", name = "GREEK SMALL LETTER MU" },
	{ symbol = "ν", digraph = "n*", name = "GREEK SMALL LETTER NU" },
	{ symbol = "ξ", digraph = "c*", name = "GREEK SMALL LETTER XI" },
	{ symbol = "ο", digraph = "o*", name = "GREEK SMALL LETTER OMICRON" },
	{ symbol = "π", digraph = "p*", name = "GREEK SMALL LETTER PI" },
	{ symbol = "ρ", digraph = "r*", name = "GREEK SMALL LETTER RHO" },
	{ symbol = "ς", digraph = "*s", name = "GREEK SMALL LETTER FINAL SIGMA" },
	{ symbol = "σ", digraph = "s*", name = "GREEK SMALL LETTER SIGMA" },
	{ symbol = "τ", digraph = "t*", name = "GREEK SMALL LETTER TAU" },
	{ symbol = "υ", digraph = "u*", name = "GREEK SMALL LETTER UPSILON" },
	{ symbol = "φ", digraph = "f*", name = "GREEK SMALL LETTER PHI" },
	{ symbol = "χ", digraph = "x*", name = "GREEK SMALL LETTER CHI" },
	{ symbol = "ψ", digraph = "q*", name = "GREEK SMALL LETTER PSI" },
	{ symbol = "ω", digraph = "w*", name = "GREEK SMALL LETTER OMEGA" },
	{ symbol = "ϊ", digraph = "j*", name = "GREEK SMALL LETTER IOTA WITH DIALYTIKA" },
	{ symbol = "ϋ", digraph = "v*", name = "GREEK SMALL LETTER UPSILON WITH DIALYTIKA" },
	{ symbol = "ό", digraph = "o%", name = "GREEK SMALL LETTER OMICRON WITH TONOS" },
	{ symbol = "ύ", digraph = "u%", name = "GREEK SMALL LETTER UPSILON WITH TONOS" },
	{ symbol = "ώ", digraph = "w%", name = "GREEK SMALL LETTER OMEGA WITH TONOS" },
	{ symbol = "Ϙ", digraph = "'G", name = "GREEK LETTER ARCHAIC KOPPA" },
	{ symbol = "ϙ", digraph = ",G", name = "GREEK SMALL LETTER ARCHAIC KOPPA" },
	{ symbol = "Ϛ", digraph = "T3", name = "GREEK LETTER STIGMA" },
	{ symbol = "ϛ", digraph = "t3", name = "GREEK SMALL LETTER STIGMA" },
	{ symbol = "Ϝ", digraph = "M3", name = "GREEK LETTER DIGAMMA" },
	{ symbol = "ϝ", digraph = "m3", name = "GREEK SMALL LETTER DIGAMMA" },
	{ symbol = "Ϟ", digraph = "K3", name = "GREEK LETTER KOPPA" },
	{ symbol = "ϟ", digraph = "k3", name = "GREEK SMALL LETTER KOPPA" },
	{ symbol = "Ϡ", digraph = "P3", name = "GREEK LETTER SAMPI" },
	{ symbol = "ϡ", digraph = "p3", name = "GREEK SMALL LETTER SAMPI" },
	{ symbol = "ϴ", digraph = "'%", name = "GREEK CAPITAL THETA SYMBOL" },
	{ symbol = "ϵ", digraph = "j3", name = "GREEK LUNATE EPSILON SYMBOL" },
	{ symbol = "Ё", digraph = "IO", name = "CYRILLIC CAPITAL LETTER IO" },
	{ symbol = "Ђ", digraph = "D%", name = "CYRILLIC CAPITAL LETTER DJE" },
	{ symbol = "Ѓ", digraph = "G%", name = "CYRILLIC CAPITAL LETTER GJE" },
	{ symbol = "Є", digraph = "IE", name = "CYRILLIC CAPITAL LETTER UKRAINIAN IE" },
	{ symbol = "Ѕ", digraph = "DS", name = "CYRILLIC CAPITAL LETTER DZE" },
	{ symbol = "І", digraph = "II", name = "CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I" },
	{ symbol = "Ї", digraph = "YI", name = "CYRILLIC CAPITAL LETTER YI" },
	{ symbol = "Ј", digraph = "J%", name = "CYRILLIC CAPITAL LETTER JE" },
	{ symbol = "Љ", digraph = "LJ", name = "CYRILLIC CAPITAL LETTER LJE" },
	{ symbol = "Њ", digraph = "NJ", name = "CYRILLIC CAPITAL LETTER NJE" },
	{ symbol = "Ћ", digraph = "Ts", name = "CYRILLIC CAPITAL LETTER TSHE" },
	{ symbol = "Ќ", digraph = "KJ", name = "CYRILLIC CAPITAL LETTER KJE" },
	{ symbol = "Ў", digraph = "V%", name = "CYRILLIC CAPITAL LETTER SHORT U" },
	{ symbol = "Џ", digraph = "DZ", name = "CYRILLIC CAPITAL LETTER DZHE" },
	{ symbol = "А", digraph = "A=", name = "CYRILLIC CAPITAL LETTER A" },
	{ symbol = "Б", digraph = "B=", name = "CYRILLIC CAPITAL LETTER BE" },
	{ symbol = "В", digraph = "V=", name = "CYRILLIC CAPITAL LETTER VE" },
	{ symbol = "Г", digraph = "G=", name = "CYRILLIC CAPITAL LETTER GHE" },
	{ symbol = "Д", digraph = "D=", name = "CYRILLIC CAPITAL LETTER DE" },
	{ symbol = "Е", digraph = "E=", name = "CYRILLIC CAPITAL LETTER IE" },
	{ symbol = "Ж", digraph = "Z%", name = "CYRILLIC CAPITAL LETTER ZHE" },
	{ symbol = "З", digraph = "Z=", name = "CYRILLIC CAPITAL LETTER ZE" },
	{ symbol = "И", digraph = "I=", name = "CYRILLIC CAPITAL LETTER I" },
	{ symbol = "Й", digraph = "J=", name = "CYRILLIC CAPITAL LETTER SHORT I" },
	{ symbol = "К", digraph = "K=", name = "CYRILLIC CAPITAL LETTER KA" },
	{ symbol = "Л", digraph = "L=", name = "CYRILLIC CAPITAL LETTER EL" },
	{ symbol = "М", digraph = "M=", name = "CYRILLIC CAPITAL LETTER EM" },
	{ symbol = "Н", digraph = "N=", name = "CYRILLIC CAPITAL LETTER EN" },
	{ symbol = "О", digraph = "O=", name = "CYRILLIC CAPITAL LETTER O" },
	{ symbol = "П", digraph = "P=", name = "CYRILLIC CAPITAL LETTER PE" },
	{ symbol = "Р", digraph = "R=", name = "CYRILLIC CAPITAL LETTER ER" },
	{ symbol = "С", digraph = "S=", name = "CYRILLIC CAPITAL LETTER ES" },
	{ symbol = "Т", digraph = "T=", name = "CYRILLIC CAPITAL LETTER TE" },
	{ symbol = "У", digraph = "U=", name = "CYRILLIC CAPITAL LETTER U" },
	{ symbol = "Ф", digraph = "F=", name = "CYRILLIC CAPITAL LETTER EF" },
	{ symbol = "Х", digraph = "H=", name = "CYRILLIC CAPITAL LETTER HA" },
	{ symbol = "Ц", digraph = "C=", name = "CYRILLIC CAPITAL LETTER TSE" },
	{ symbol = "Ч", digraph = "C%", name = "CYRILLIC CAPITAL LETTER CHE" },
	{ symbol = "Ш", digraph = "S%", name = "CYRILLIC CAPITAL LETTER SHA" },
	{ symbol = "Щ", digraph = "Sc", name = "CYRILLIC CAPITAL LETTER SHCHA" },
	{ symbol = "Ъ", digraph = '="', name = "CYRILLIC CAPITAL LETTER HARD SIGN" },
	{ symbol = "Ы", digraph = "Y=", name = "CYRILLIC CAPITAL LETTER YERU" },
	{ symbol = "Ь", digraph = '%"', name = "CYRILLIC CAPITAL LETTER SOFT SIGN" },
	{ symbol = "Э", digraph = "JE", name = "CYRILLIC CAPITAL LETTER E" },
	{ symbol = "Ю", digraph = "JU", name = "CYRILLIC CAPITAL LETTER YU" },
	{ symbol = "Я", digraph = "JA", name = "CYRILLIC CAPITAL LETTER YA" },
	{ symbol = "а", digraph = "a=", name = "CYRILLIC SMALL LETTER A" },
	{ symbol = "б", digraph = "b=", name = "CYRILLIC SMALL LETTER BE" },
	{ symbol = "в", digraph = "v=", name = "CYRILLIC SMALL LETTER VE" },
	{ symbol = "г", digraph = "g=", name = "CYRILLIC SMALL LETTER GHE" },
	{ symbol = "д", digraph = "d=", name = "CYRILLIC SMALL LETTER DE" },
	{ symbol = "е", digraph = "e=", name = "CYRILLIC SMALL LETTER IE" },
	{ symbol = "ж", digraph = "z%", name = "CYRILLIC SMALL LETTER ZHE" },
	{ symbol = "з", digraph = "z=", name = "CYRILLIC SMALL LETTER ZE" },
	{ symbol = "и", digraph = "i=", name = "CYRILLIC SMALL LETTER I" },
	{ symbol = "й", digraph = "j=", name = "CYRILLIC SMALL LETTER SHORT I" },
	{ symbol = "к", digraph = "k=", name = "CYRILLIC SMALL LETTER KA" },
	{ symbol = "л", digraph = "l=", name = "CYRILLIC SMALL LETTER EL" },
	{ symbol = "м", digraph = "m=", name = "CYRILLIC SMALL LETTER EM" },
	{ symbol = "н", digraph = "n=", name = "CYRILLIC SMALL LETTER EN" },
	{ symbol = "о", digraph = "o=", name = "CYRILLIC SMALL LETTER O" },
	{ symbol = "п", digraph = "p=", name = "CYRILLIC SMALL LETTER PE" },
	{ symbol = "р", digraph = "r=", name = "CYRILLIC SMALL LETTER ER" },
	{ symbol = "с", digraph = "s=", name = "CYRILLIC SMALL LETTER ES" },
	{ symbol = "т", digraph = "t=", name = "CYRILLIC SMALL LETTER TE" },
	{ symbol = "у", digraph = "u=", name = "CYRILLIC SMALL LETTER U" },
	{ symbol = "ф", digraph = "f=", name = "CYRILLIC SMALL LETTER EF" },
	{ symbol = "х", digraph = "h=", name = "CYRILLIC SMALL LETTER HA" },
	{ symbol = "ц", digraph = "c=", name = "CYRILLIC SMALL LETTER TSE" },
	{ symbol = "ч", digraph = "c%", name = "CYRILLIC SMALL LETTER CHE" },
	{ symbol = "ш", digraph = "s%", name = "CYRILLIC SMALL LETTER SHA" },
	{ symbol = "щ", digraph = "sc", name = "CYRILLIC SMALL LETTER SHCHA" },
	{ symbol = "ъ", digraph = "='", name = "CYRILLIC SMALL LETTER HARD SIGN" },
	{ symbol = "ы", digraph = "y=", name = "CYRILLIC SMALL LETTER YERU" },
	{ symbol = "ь", digraph = "%'", name = "CYRILLIC SMALL LETTER SOFT SIGN" },
	{ symbol = "э", digraph = "je", name = "CYRILLIC SMALL LETTER E" },
	{ symbol = "ю", digraph = "ju", name = "CYRILLIC SMALL LETTER YU" },
	{ symbol = "я", digraph = "ja", name = "CYRILLIC SMALL LETTER YA" },
	{ symbol = "ё", digraph = "io", name = "CYRILLIC SMALL LETTER IO" },
	{ symbol = "ђ", digraph = "d%", name = "CYRILLIC SMALL LETTER DJE" },
	{ symbol = "ѓ", digraph = "g%", name = "CYRILLIC SMALL LETTER GJE" },
	{ symbol = "є", digraph = "ie", name = "CYRILLIC SMALL LETTER UKRAINIAN IE" },
	{ symbol = "ѕ", digraph = "ds", name = "CYRILLIC SMALL LETTER DZE" },
	{ symbol = "і", digraph = "ii", name = "CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I" },
	{ symbol = "ї", digraph = "yi", name = "CYRILLIC SMALL LETTER YI" },
	{ symbol = "ј", digraph = "j%", name = "CYRILLIC SMALL LETTER JE" },
	{ symbol = "љ", digraph = "lj", name = "CYRILLIC SMALL LETTER LJE" },
	{ symbol = "њ", digraph = "nj", name = "CYRILLIC SMALL LETTER NJE" },
	{ symbol = "ћ", digraph = "ts", name = "CYRILLIC SMALL LETTER TSHE" },
	{ symbol = "ќ", digraph = "kj", name = "CYRILLIC SMALL LETTER KJE" },
	{ symbol = "ў", digraph = "v%", name = "CYRILLIC SMALL LETTER SHORT U" },
	{ symbol = "џ", digraph = "dz", name = "CYRILLIC SMALL LETTER DZHE" },
	{ symbol = "Ѣ", digraph = "Y3", name = "CYRILLIC CAPITAL LETTER YAT" },
	{ symbol = "ѣ", digraph = "y3", name = "CYRILLIC SMALL LETTER YAT" },
	{ symbol = "Ѫ", digraph = "O3", name = "CYRILLIC CAPITAL LETTER BIG YUS" },
	{ symbol = "ѫ", digraph = "o3", name = "CYRILLIC SMALL LETTER BIG YUS" },
	{ symbol = "Ѳ", digraph = "F3", name = "CYRILLIC CAPITAL LETTER FITA" },
	{ symbol = "ѳ", digraph = "f3", name = "CYRILLIC SMALL LETTER FITA" },
	{ symbol = "Ѵ", digraph = "V3", name = "CYRILLIC CAPITAL LETTER IZHITSA" },
	{ symbol = "ѵ", digraph = "v3", name = "CYRILLIC SMALL LETTER IZHITSA" },
	{ symbol = "Ҁ", digraph = "C3", name = "CYRILLIC CAPITAL LETTER KOPPA" },
	{ symbol = "ҁ", digraph = "c3", name = "CYRILLIC SMALL LETTER KOPPA" },
	{ symbol = "Ґ", digraph = "G3", name = "CYRILLIC CAPITAL LETTER GHE WITH UPTURN" },
	{ symbol = "ґ", digraph = "g3", name = "CYRILLIC SMALL LETTER GHE WITH UPTURN" },
	{ symbol = "א", digraph = "A+", name = "HEBREW LETTER ALEF" },
	{ symbol = "ב", digraph = "B+", name = "HEBREW LETTER BET" },
	{ symbol = "ג", digraph = "G+", name = "HEBREW LETTER GIMEL" },
	{ symbol = "ד", digraph = "D+", name = "HEBREW LETTER DALET" },
	{ symbol = "ה", digraph = "H+", name = "HEBREW LETTER HE" },
	{ symbol = "ו", digraph = "W+", name = "HEBREW LETTER VAV" },
	{ symbol = "ז", digraph = "Z+", name = "HEBREW LETTER ZAYIN" },
	{ symbol = "ח", digraph = "X+", name = "HEBREW LETTER HET" },
	{ symbol = "ט", digraph = "Tj", name = "HEBREW LETTER TET" },
	{ symbol = "י", digraph = "J+", name = "HEBREW LETTER YOD" },
	{ symbol = "ך", digraph = "K%", name = "HEBREW LETTER FINAL KAF" },
	{ symbol = "כ", digraph = "K+", name = "HEBREW LETTER KAF" },
	{ symbol = "ל", digraph = "L+", name = "HEBREW LETTER LAMED" },
	{ symbol = "ם", digraph = "M%", name = "HEBREW LETTER FINAL MEM" },
	{ symbol = "מ", digraph = "M+", name = "HEBREW LETTER MEM" },
	{ symbol = "ן", digraph = "N%", name = "HEBREW LETTER FINAL NUN `" },
	{ symbol = "נ", digraph = "N+", name = "HEBREW LETTER NUN `" },
	{ symbol = "ס", digraph = "S+", name = "HEBREW LETTER SAMEKH" },
	{ symbol = "ע", digraph = "E+", name = "HEBREW LETTER AYIN" },
	{ symbol = "ף", digraph = "P%", name = "HEBREW LETTER FINAL PE" },
	{ symbol = "פ", digraph = "P+", name = "HEBREW LETTER PE" },
	{ symbol = "ץ", digraph = "Zj", name = "HEBREW LETTER FINAL TSADI" },
	{ symbol = "צ", digraph = "ZJ", name = "HEBREW LETTER TSADI" },
	{ symbol = "ק", digraph = "Q+", name = "HEBREW LETTER QOF" },
	{ symbol = "ר", digraph = "R+", name = "HEBREW LETTER RESH" },
	{ symbol = "ש", digraph = "Sh", name = "HEBREW LETTER SHIN" },
	{ symbol = "ת", digraph = "T+", name = "HEBREW LETTER TAV" },
	{ symbol = "،", digraph = ",+", name = "ARABIC COMMA" },
	{ symbol = "؛", digraph = ";+", name = "ARABIC SEMICOLON" },
	{ symbol = "؟", digraph = "?+", name = "ARABIC QUESTION MARK" },
	{ symbol = "ء", digraph = "H'", name = "ARABIC LETTER HAMZA" },
	{ symbol = "آ", digraph = "aM", name = "ARABIC LETTER ALEF WITH MADDA ABOVE" },
	{ symbol = "أ", digraph = "aH", name = "ARABIC LETTER ALEF WITH HAMZA ABOVE" },
	{ symbol = "ؤ", digraph = "wH", name = "ARABIC LETTER WAW WITH HAMZA ABOVE" },
	{ symbol = "إ", digraph = "ah", name = "ARABIC LETTER ALEF WITH HAMZA BELOW" },
	{ symbol = "ئ", digraph = "yH", name = "ARABIC LETTER YEH WITH HAMZA ABOVE" },
	{ symbol = "ا", digraph = "a+", name = "ARABIC LETTER ALEF" },
	{ symbol = "ب", digraph = "b+", name = "ARABIC LETTER BEH" },
	{ symbol = "ة", digraph = "tm", name = "ARABIC LETTER TEH MARBUTA" },
	{ symbol = "ت", digraph = "t+", name = "ARABIC LETTER TEH" },
	{ symbol = "ث", digraph = "tk", name = "ARABIC LETTER THEH" },
	{ symbol = "ج", digraph = "g+", name = "ARABIC LETTER JEEM" },
	{ symbol = "ح", digraph = "hk", name = "ARABIC LETTER HAH" },
	{ symbol = "خ", digraph = "x+", name = "ARABIC LETTER KHAH" },
	{ symbol = "د", digraph = "d+", name = "ARABIC LETTER DAL" },
	{ symbol = "ذ", digraph = "dk", name = "ARABIC LETTER THAL" },
	{ symbol = "ر", digraph = "r+", name = "ARABIC LETTER REH" },
	{ symbol = "ز", digraph = "z+", name = "ARABIC LETTER ZAIN" },
	{ symbol = "س", digraph = "s+", name = "ARABIC LETTER SEEN" },
	{ symbol = "ش", digraph = "sn", name = "ARABIC LETTER SHEEN" },
	{ symbol = "ص", digraph = "c+", name = "ARABIC LETTER SAD" },
	{ symbol = "ض", digraph = "dd", name = "ARABIC LETTER DAD" },
	{ symbol = "ط", digraph = "tj", name = "ARABIC LETTER TAH" },
	{ symbol = "ظ", digraph = "zH", name = "ARABIC LETTER ZAH" },
	{ symbol = "ع", digraph = "e+", name = "ARABIC LETTER AIN" },
	{ symbol = "غ", digraph = "i+", name = "ARABIC LETTER GHAIN" },
	{ symbol = "ـ", digraph = "++", name = "ARABIC TATWEEL" },
	{ symbol = "ف", digraph = "f+", name = "ARABIC LETTER FEH" },
	{ symbol = "ق", digraph = "q+", name = "ARABIC LETTER QAF" },
	{ symbol = "ك", digraph = "k+", name = "ARABIC LETTER KAF" },
	{ symbol = "ل", digraph = "l+", name = "ARABIC LETTER LAM" },
	{ symbol = "م", digraph = "m+", name = "ARABIC LETTER MEEM" },
	{ symbol = "ن", digraph = "n+", name = "ARABIC LETTER NOON" },
	{ symbol = "ه", digraph = "h+", name = "ARABIC LETTER HEH" },
	{ symbol = "و", digraph = "w+", name = "ARABIC LETTER WAW" },
	{ symbol = "ى", digraph = "j+", name = "ARABIC LETTER ALEF MAKSURA" },
	{ symbol = "ي", digraph = "y+", name = "ARABIC LETTER YEH" },
	{ symbol = "ً", digraph = ":+", name = "FATHATAN" },
	{ symbol = "ٌ", digraph = '"+', name = "DAMMATAN" },
	{ symbol = "ٍ", digraph = "=+", name = "KASRATAN" },
	{ symbol = "َ", digraph = "/+", name = "FATHA" },
	{ symbol = "ُ", digraph = "'+", name = "DAMMA" },
	{ symbol = "ِ", digraph = "1+", name = "KASRA" },
	{ symbol = "ّ", digraph = "3+", name = "SHADDA" },
	{ symbol = "ْ", digraph = "0+", name = "SUKUN" },
	{ symbol = "ٰ", digraph = "aS", name = "LETTER SUPERSCRIPT ALEF" },
	{ symbol = "پ", digraph = "p+", name = "ARABIC LETTER PEH" },
	{ symbol = "ڤ", digraph = "v+", name = "ARABIC LETTER VEH" },
	{ symbol = "گ", digraph = "gf", name = "ARABIC LETTER GAF" },
	{ symbol = "۰", digraph = "0a", name = "EXTENDED ARABIC-INDIC DIGIT ZERO" },
	{ symbol = "۱", digraph = "1a", name = "EXTENDED ARABIC-INDIC DIGIT ONE" },
	{ symbol = "۲", digraph = "2a", name = "EXTENDED ARABIC-INDIC DIGIT TWO" },
	{ symbol = "۳", digraph = "3a", name = "EXTENDED ARABIC-INDIC DIGIT THREE" },
	{ symbol = "۴", digraph = "4a", name = "EXTENDED ARABIC-INDIC DIGIT FOUR" },
	{ symbol = "۵", digraph = "5a", name = "EXTENDED ARABIC-INDIC DIGIT FIVE" },
	{ symbol = "۶", digraph = "6a", name = "EXTENDED ARABIC-INDIC DIGIT SIX" },
	{ symbol = "۷", digraph = "7a", name = "EXTENDED ARABIC-INDIC DIGIT SEVEN" },
	{ symbol = "۸", digraph = "8a", name = "EXTENDED ARABIC-INDIC DIGIT EIGHT" },
	{ symbol = "۹", digraph = "9a", name = "EXTENDED ARABIC-INDIC DIGIT NINE" },
	{ symbol = "Ḃ", digraph = "B.", name = "LATIN CAPITAL LETTER B WITH DOT ABOVE" },
	{ symbol = "ḃ", digraph = "b.", name = "LATIN SMALL LETTER B WITH DOT ABOVE" },
	{ symbol = "Ḇ", digraph = "B_", name = "LATIN CAPITAL LETTER B WITH LINE BELOW" },
	{ symbol = "ḇ", digraph = "b_", name = "LATIN SMALL LETTER B WITH LINE BELOW" },
	{ symbol = "Ḋ", digraph = "D.", name = "LATIN CAPITAL LETTER D WITH DOT ABOVE" },
	{ symbol = "ḋ", digraph = "d.", name = "LATIN SMALL LETTER D WITH DOT ABOVE" },
	{ symbol = "Ḏ", digraph = "D_", name = "LATIN CAPITAL LETTER D WITH LINE BELOW" },
	{ symbol = "ḏ", digraph = "d_", name = "LATIN SMALL LETTER D WITH LINE BELOW" },
	{ symbol = "Ḑ", digraph = "D,", name = "LATIN CAPITAL LETTER D WITH CEDILLA" },
	{ symbol = "ḑ", digraph = "d,", name = "LATIN SMALL LETTER D WITH CEDILLA" },
	{ symbol = "Ḟ", digraph = "F.", name = "LATIN CAPITAL LETTER F WITH DOT ABOVE" },
	{ symbol = "ḟ", digraph = "f.", name = "LATIN SMALL LETTER F WITH DOT ABOVE" },
	{ symbol = "Ḡ", digraph = "G-", name = "LATIN CAPITAL LETTER G WITH MACRON" },
	{ symbol = "ḡ", digraph = "g-", name = "LATIN SMALL LETTER G WITH MACRON" },
	{ symbol = "Ḣ", digraph = "H.", name = "LATIN CAPITAL LETTER H WITH DOT ABOVE" },
	{ symbol = "ḣ", digraph = "h.", name = "LATIN SMALL LETTER H WITH DOT ABOVE" },
	{ symbol = "Ḧ", digraph = "H:", name = "LATIN CAPITAL LETTER H WITH DIAERESIS" },
	{ symbol = "ḧ", digraph = "h:", name = "LATIN SMALL LETTER H WITH DIAERESIS" },
	{ symbol = "Ḩ", digraph = "H,", name = "LATIN CAPITAL LETTER H WITH CEDILLA" },
	{ symbol = "ḩ", digraph = "h,", name = "LATIN SMALL LETTER H WITH CEDILLA" },
	{ symbol = "Ḱ", digraph = "K'", name = "LATIN CAPITAL LETTER K WITH ACUTE" },
	{ symbol = "ḱ", digraph = "k'", name = "LATIN SMALL LETTER K WITH ACUTE" },
	{ symbol = "Ḵ", digraph = "K_", name = "LATIN CAPITAL LETTER K WITH LINE BELOW" },
	{ symbol = "ḵ", digraph = "k_", name = "LATIN SMALL LETTER K WITH LINE BELOW" },
	{ symbol = "Ḻ", digraph = "L_", name = "LATIN CAPITAL LETTER L WITH LINE BELOW" },
	{ symbol = "ḻ", digraph = "l_", name = "LATIN SMALL LETTER L WITH LINE BELOW" },
	{ symbol = "Ḿ", digraph = "M'", name = "LATIN CAPITAL LETTER M WITH ACUTE" },
	{ symbol = "ḿ", digraph = "m'", name = "LATIN SMALL LETTER M WITH ACUTE" },
	{ symbol = "Ṁ", digraph = "M.", name = "LATIN CAPITAL LETTER M WITH DOT ABOVE" },
	{ symbol = "ṁ", digraph = "m.", name = "LATIN SMALL LETTER M WITH DOT ABOVE" },
	{ symbol = "Ṅ", digraph = "N.", name = "LATIN CAPITAL LETTER N WITH DOT ABOVE `" },
	{ symbol = "ṅ", digraph = "n.", name = "LATIN SMALL LETTER N WITH DOT ABOVE `" },
	{ symbol = "Ṉ", digraph = "N_", name = "LATIN CAPITAL LETTER N WITH LINE BELOW `" },
	{ symbol = "ṉ", digraph = "n_", name = "LATIN SMALL LETTER N WITH LINE BELOW `" },
	{ symbol = "Ṕ", digraph = "P'", name = "LATIN CAPITAL LETTER P WITH ACUTE" },
	{ symbol = "ṕ", digraph = "p'", name = "LATIN SMALL LETTER P WITH ACUTE" },
	{ symbol = "Ṗ", digraph = "P.", name = "LATIN CAPITAL LETTER P WITH DOT ABOVE" },
	{ symbol = "ṗ", digraph = "p.", name = "LATIN SMALL LETTER P WITH DOT ABOVE" },
	{ symbol = "Ṙ", digraph = "R.", name = "LATIN CAPITAL LETTER R WITH DOT ABOVE" },
	{ symbol = "ṙ", digraph = "r.", name = "LATIN SMALL LETTER R WITH DOT ABOVE" },
	{ symbol = "Ṟ", digraph = "R_", name = "LATIN CAPITAL LETTER R WITH LINE BELOW" },
	{ symbol = "ṟ", digraph = "r_", name = "LATIN SMALL LETTER R WITH LINE BELOW" },
	{ symbol = "Ṡ", digraph = "S.", name = "LATIN CAPITAL LETTER S WITH DOT ABOVE" },
	{ symbol = "ṡ", digraph = "s.", name = "LATIN SMALL LETTER S WITH DOT ABOVE" },
	{ symbol = "Ṫ", digraph = "T.", name = "LATIN CAPITAL LETTER T WITH DOT ABOVE" },
	{ symbol = "ṫ", digraph = "t.", name = "LATIN SMALL LETTER T WITH DOT ABOVE" },
	{ symbol = "Ṯ", digraph = "T_", name = "LATIN CAPITAL LETTER T WITH LINE BELOW" },
	{ symbol = "ṯ", digraph = "t_", name = "LATIN SMALL LETTER T WITH LINE BELOW" },
	{ symbol = "Ṽ", digraph = "V?", name = "LATIN CAPITAL LETTER V WITH TILDE" },
	{ symbol = "ṽ", digraph = "v?", name = "LATIN SMALL LETTER V WITH TILDE" },
	{ symbol = "Ẁ", digraph = "W!", name = "LATIN CAPITAL LETTER W WITH GRAVE" },
	{ symbol = "ẁ", digraph = "w!", name = "LATIN SMALL LETTER W WITH GRAVE" },
	{ symbol = "Ẃ", digraph = "W'", name = "LATIN CAPITAL LETTER W WITH ACUTE" },
	{ symbol = "ẃ", digraph = "w'", name = "LATIN SMALL LETTER W WITH ACUTE" },
	{ symbol = "Ẅ", digraph = "W:", name = "LATIN CAPITAL LETTER W WITH DIAERESIS" },
	{ symbol = "ẅ", digraph = "w:", name = "LATIN SMALL LETTER W WITH DIAERESIS" },
	{ symbol = "Ẇ", digraph = "W.", name = "LATIN CAPITAL LETTER W WITH DOT ABOVE" },
	{ symbol = "ẇ", digraph = "w.", name = "LATIN SMALL LETTER W WITH DOT ABOVE" },
	{ symbol = "Ẋ", digraph = "X.", name = "LATIN CAPITAL LETTER X WITH DOT ABOVE" },
	{ symbol = "ẋ", digraph = "x.", name = "LATIN SMALL LETTER X WITH DOT ABOVE" },
	{ symbol = "Ẍ", digraph = "X:", name = "LATIN CAPITAL LETTER X WITH DIAERESIS" },
	{ symbol = "ẍ", digraph = "x:", name = "LATIN SMALL LETTER X WITH DIAERESIS" },
	{ symbol = "Ẏ", digraph = "Y.", name = "LATIN CAPITAL LETTER Y WITH DOT ABOVE" },
	{ symbol = "ẏ", digraph = "y.", name = "LATIN SMALL LETTER Y WITH DOT ABOVE" },
	{ symbol = "Ẑ", digraph = "Z>", name = "LATIN CAPITAL LETTER Z WITH CIRCUMFLEX" },
	{ symbol = "ẑ", digraph = "z>", name = "LATIN SMALL LETTER Z WITH CIRCUMFLEX" },
	{ symbol = "Ẕ", digraph = "Z_", name = "LATIN CAPITAL LETTER Z WITH LINE BELOW" },
	{ symbol = "ẕ", digraph = "z_", name = "LATIN SMALL LETTER Z WITH LINE BELOW" },
	{ symbol = "ẖ", digraph = "h_", name = "LATIN SMALL LETTER H WITH LINE BELOW" },
	{ symbol = "ẗ", digraph = "t:", name = "LATIN SMALL LETTER T WITH DIAERESIS" },
	{ symbol = "ẘ", digraph = "w0", name = "LATIN SMALL LETTER W WITH RING ABOVE" },
	{ symbol = "ẙ", digraph = "y0", name = "LATIN SMALL LETTER Y WITH RING ABOVE" },
	{ symbol = "Ả", digraph = "A2", name = "LATIN CAPITAL LETTER A WITH HOOK ABOVE" },
	{ symbol = "ả", digraph = "a2", name = "LATIN SMALL LETTER A WITH HOOK ABOVE" },
	{ symbol = "Ẻ", digraph = "E2", name = "LATIN CAPITAL LETTER E WITH HOOK ABOVE" },
	{ symbol = "ẻ", digraph = "e2", name = "LATIN SMALL LETTER E WITH HOOK ABOVE" },
	{ symbol = "Ẽ", digraph = "E?", name = "LATIN CAPITAL LETTER E WITH TILDE" },
	{ symbol = "ẽ", digraph = "e?", name = "LATIN SMALL LETTER E WITH TILDE" },
	{ symbol = "Ỉ", digraph = "I2", name = "LATIN CAPITAL LETTER I WITH HOOK ABOVE" },
	{ symbol = "ỉ", digraph = "i2", name = "LATIN SMALL LETTER I WITH HOOK ABOVE" },
	{ symbol = "Ỏ", digraph = "O2", name = "LATIN CAPITAL LETTER O WITH HOOK ABOVE" },
	{ symbol = "ỏ", digraph = "o2", name = "LATIN SMALL LETTER O WITH HOOK ABOVE" },
	{ symbol = "Ủ", digraph = "U2", name = "LATIN CAPITAL LETTER U WITH HOOK ABOVE" },
	{ symbol = "ủ", digraph = "u2", name = "LATIN SMALL LETTER U WITH HOOK ABOVE" },
	{ symbol = "Ỳ", digraph = "Y!", name = "LATIN CAPITAL LETTER Y WITH GRAVE" },
	{ symbol = "ỳ", digraph = "y!", name = "LATIN SMALL LETTER Y WITH GRAVE" },
	{ symbol = "Ỷ", digraph = "Y2", name = "LATIN CAPITAL LETTER Y WITH HOOK ABOVE" },
	{ symbol = "ỷ", digraph = "y2", name = "LATIN SMALL LETTER Y WITH HOOK ABOVE" },
	{ symbol = "Ỹ", digraph = "Y?", name = "LATIN CAPITAL LETTER Y WITH TILDE" },
	{ symbol = "ỹ", digraph = "y?", name = "LATIN SMALL LETTER Y WITH TILDE" },
	{ symbol = "ἀ", digraph = ";'", name = "GREEK SMALL LETTER ALPHA WITH PSILI" },
	{ symbol = "ἁ", digraph = ",'", name = "GREEK SMALL LETTER ALPHA WITH DASIA" },
	{ symbol = "ἂ", digraph = ";!", name = "GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA" },
	{ symbol = "ἃ", digraph = ",!", name = "GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA" },
	{ symbol = "ἄ", digraph = "?;", name = "GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA" },
	{ symbol = "ἅ", digraph = "?,", name = "GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA" },
	{ symbol = "ἆ", digraph = "!:", name = "GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI" },
	{ symbol = "ἇ", digraph = "?:", name = "GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI" },
	{ symbol = "‐", digraph = "-1", name = "HYPHEN" },
	{ symbol = "–", digraph = "-N", name = "EN DASH `" },
	{ symbol = "—", digraph = "-M", name = "EM DASH" },
	{ symbol = "―", digraph = "-3", name = "HORIZONTAL BAR" },
	{ symbol = "‖", digraph = "!2", name = "DOUBLE VERTICAL LINE" },
	{ symbol = "‗", digraph = "=2", name = "DOUBLE LOW LINE" },
	{ symbol = "‘", digraph = "'6", name = "LEFT SINGLE QUOTATION MARK" },
	{ symbol = "’", digraph = "'9", name = "RIGHT SINGLE QUOTATION MARK" },
	{ symbol = "‚", digraph = ".9", name = "SINGLE LOW-9 QUOTATION MARK" },
	{ symbol = "‛", digraph = "9'", name = "SINGLE HIGH-REVERSED-9 QUOTATION MARK" },
	{ symbol = "“", digraph = '"6', name = "LEFT DOUBLE QUOTATION MARK" },
	{ symbol = "”", digraph = '"9', name = "RIGHT DOUBLE QUOTATION MARK" },
	{ symbol = "„", digraph = ":9", name = "DOUBLE LOW-9 QUOTATION MARK" },
	{ symbol = "‟", digraph = '9"', name = "DOUBLE HIGH-REVERSED-9 QUOTATION MARK" },
	{ symbol = "†", digraph = "/-", name = "DAGGER" },
	{ symbol = "‡", digraph = "/=", name = "DOUBLE DAGGER" },
	{ symbol = "•", digraph = "oo", name = "BULLET" },
	{ symbol = "‥", digraph = "..", name = "TWO DOT LEADER" },
	{ symbol = "…", digraph = ",.", name = "HORIZONTAL ELLIPSIS" },
	{ symbol = "‰", digraph = "%0", name = "PER MILLE SIGN" },
	{ symbol = "′", digraph = "1'", name = "PRIME" },
	{ symbol = "″", digraph = "2'", name = "DOUBLE PRIME" },
	{ symbol = "‴", digraph = "3'", name = "TRIPLE PRIME" },
	{ symbol = "⁗", digraph = "4'", name = "QUADRUPLE PRIME" },
	{ symbol = "‵", digraph = '1"', name = "REVERSED PRIME" },
	{ symbol = "‶", digraph = '2"', name = "REVERSED DOUBLE PRIME" },
	{ symbol = "‷", digraph = '3"', name = "REVERSED TRIPLE PRIME" },
	{ symbol = "‸", digraph = "Ca", name = "CARET" },
	{ symbol = "‹", digraph = "<1", name = "SINGLE LEFT-POINTING ANGLE QUOTATION MARK" },
	{ symbol = "›", digraph = ">1", name = "SINGLE RIGHT-POINTING ANGLE QUOTATION MARK" },
	{ symbol = "※", digraph = ":X", name = "REFERENCE MARK" },
	{ symbol = "‾", digraph = "'-", name = "OVERLINE" },
	{ symbol = "⁄", digraph = "/f", name = "FRACTION SLASH" },
	{ symbol = "⁰", digraph = "0S", name = "SUPERSCRIPT ZERO" },
	{ symbol = "⁴", digraph = "4S", name = "SUPERSCRIPT FOUR" },
	{ symbol = "⁵", digraph = "5S", name = "SUPERSCRIPT FIVE" },
	{ symbol = "⁶", digraph = "6S", name = "SUPERSCRIPT SIX" },
	{ symbol = "⁷", digraph = "7S", name = "SUPERSCRIPT SEVEN" },
	{ symbol = "⁸", digraph = "8S", name = "SUPERSCRIPT EIGHT" },
	{ symbol = "⁹", digraph = "9S", name = "SUPERSCRIPT NINE" },
	{ symbol = "⁺", digraph = "+S", name = "SUPERSCRIPT PLUS SIGN" },
	{ symbol = "⁻", digraph = "-S", name = "SUPERSCRIPT MINUS" },
	{ symbol = "⁼", digraph = "=S", name = "SUPERSCRIPT EQUALS SIGN" },
	{ symbol = "⁽", digraph = "(S", name = "SUPERSCRIPT LEFT PARENTHESIS" },
	{ symbol = "⁾", digraph = ")S", name = "SUPERSCRIPT RIGHT PARENTHESIS" },
	{ symbol = "ⁿ", digraph = "nS", name = "SUPERSCRIPT LATIN SMALL LETTER N `" },
	{ symbol = "₀", digraph = "0s", name = "SUBSCRIPT ZERO" },
	{ symbol = "₁", digraph = "1s", name = "SUBSCRIPT ONE" },
	{ symbol = "₂", digraph = "2s", name = "SUBSCRIPT TWO" },
	{ symbol = "₃", digraph = "3s", name = "SUBSCRIPT THREE" },
	{ symbol = "₄", digraph = "4s", name = "SUBSCRIPT FOUR" },
	{ symbol = "₅", digraph = "5s", name = "SUBSCRIPT FIVE" },
	{ symbol = "₆", digraph = "6s", name = "SUBSCRIPT SIX" },
	{ symbol = "₇", digraph = "7s", name = "SUBSCRIPT SEVEN" },
	{ symbol = "₈", digraph = "8s", name = "SUBSCRIPT EIGHT" },
	{ symbol = "₉", digraph = "9s", name = "SUBSCRIPT NINE" },
	{ symbol = "₊", digraph = "+s", name = "SUBSCRIPT PLUS SIGN" },
	{ symbol = "₋", digraph = "-s", name = "SUBSCRIPT MINUS" },
	{ symbol = "₌", digraph = "=s", name = "SUBSCRIPT EQUALS SIGN" },
	{ symbol = "₍", digraph = "(s", name = "SUBSCRIPT LEFT PARENTHESIS" },
	{ symbol = "₎", digraph = ")s", name = "SUBSCRIPT RIGHT PARENTHESIS" },
	{ symbol = "₤", digraph = "Li", name = "LIRA SIGN" },
	{ symbol = "₧", digraph = "Pt", name = "PESETA SIGN" },
	{ symbol = "₩", digraph = "W=", name = "WON SIGN" },
	{ symbol = "€", digraph = "Eu", name = "EURO SIGN" },
	{ symbol = "₽", digraph = "=R", name = "ROUBLE SIGN" },
	{ symbol = "₽", digraph = "=P", name = "ROUBLE SIGN" },
	{ symbol = "℃", digraph = "oC", name = "DEGREE CELSIUS" },
	{ symbol = "℅", digraph = "co", name = "CARE OF" },
	{ symbol = "℉", digraph = "oF", name = "DEGREE FAHRENHEIT" },
	{ symbol = "№", digraph = "N0", name = "NUMERO SIGN" },
	{ symbol = "℗", digraph = "PO", name = "SOUND RECORDING COPYRIGHT" },
	{ symbol = "℞", digraph = "Rx", name = "PRESCRIPTION TAKE" },
	{ symbol = "℠", digraph = "SM", name = "SERVICE MARK" },
	{ symbol = "™", digraph = "TM", name = "TRADE MARK SIGN" },
	{ symbol = "Ω", digraph = "Om", name = "OHM SIGN" },
	{ symbol = "Å", digraph = "AO", name = "ANGSTROM SIGN" },
	{ symbol = "⅓", digraph = "13", name = "VULGAR FRACTION ONE THIRD" },
	{ symbol = "⅔", digraph = "23", name = "VULGAR FRACTION TWO THIRDS" },
	{ symbol = "⅕", digraph = "15", name = "VULGAR FRACTION ONE FIFTH" },
	{ symbol = "⅖", digraph = "25", name = "VULGAR FRACTION TWO FIFTHS" },
	{ symbol = "⅗", digraph = "35", name = "VULGAR FRACTION THREE FIFTHS" },
	{ symbol = "⅘", digraph = "45", name = "VULGAR FRACTION FOUR FIFTHS" },
	{ symbol = "⅙", digraph = "16", name = "VULGAR FRACTION ONE SIXTH" },
	{ symbol = "⅚", digraph = "56", name = "VULGAR FRACTION FIVE SIXTHS" },
	{ symbol = "⅛", digraph = "18", name = "VULGAR FRACTION ONE EIGHTH" },
	{ symbol = "⅜", digraph = "38", name = "VULGAR FRACTION THREE EIGHTHS" },
	{ symbol = "⅝", digraph = "58", name = "VULGAR FRACTION FIVE EIGHTHS" },
	{ symbol = "⅞", digraph = "78", name = "VULGAR FRACTION SEVEN EIGHTHS" },
	{ symbol = "Ⅰ", digraph = "1R", name = "ROMAN NUMERAL ONE" },
	{ symbol = "Ⅱ", digraph = "2R", name = "ROMAN NUMERAL TWO" },
	{ symbol = "Ⅲ", digraph = "3R", name = "ROMAN NUMERAL THREE" },
	{ symbol = "Ⅳ", digraph = "4R", name = "ROMAN NUMERAL FOUR" },
	{ symbol = "Ⅴ", digraph = "5R", name = "ROMAN NUMERAL FIVE" },
	{ symbol = "Ⅵ", digraph = "6R", name = "ROMAN NUMERAL SIX" },
	{ symbol = "Ⅶ", digraph = "7R", name = "ROMAN NUMERAL SEVEN" },
	{ symbol = "Ⅷ", digraph = "8R", name = "ROMAN NUMERAL EIGHT" },
	{ symbol = "Ⅸ", digraph = "9R", name = "ROMAN NUMERAL NINE" },
	{ symbol = "Ⅹ", digraph = "aR", name = "ROMAN NUMERAL TEN" },
	{ symbol = "Ⅺ", digraph = "bR", name = "ROMAN NUMERAL ELEVEN" },
	{ symbol = "Ⅻ", digraph = "cR", name = "ROMAN NUMERAL TWELVE" },
	{ symbol = "ⅰ", digraph = "1r", name = "SMALL ROMAN NUMERAL ONE" },
	{ symbol = "ⅱ", digraph = "2r", name = "SMALL ROMAN NUMERAL TWO" },
	{ symbol = "ⅲ", digraph = "3r", name = "SMALL ROMAN NUMERAL THREE" },
	{ symbol = "ⅳ", digraph = "4r", name = "SMALL ROMAN NUMERAL FOUR" },
	{ symbol = "ⅴ", digraph = "5r", name = "SMALL ROMAN NUMERAL FIVE" },
	{ symbol = "ⅵ", digraph = "6r", name = "SMALL ROMAN NUMERAL SIX" },
	{ symbol = "ⅶ", digraph = "7r", name = "SMALL ROMAN NUMERAL SEVEN" },
	{ symbol = "ⅷ", digraph = "8r", name = "SMALL ROMAN NUMERAL EIGHT" },
	{ symbol = "ⅸ", digraph = "9r", name = "SMALL ROMAN NUMERAL NINE" },
	{ symbol = "ⅹ", digraph = "ar", name = "SMALL ROMAN NUMERAL TEN" },
	{ symbol = "ⅺ", digraph = "br", name = "SMALL ROMAN NUMERAL ELEVEN" },
	{ symbol = "ⅻ", digraph = "cr", name = "SMALL ROMAN NUMERAL TWELVE" },
	{ symbol = "←", digraph = "<-", name = "LEFTWARDS ARROW" },
	{ symbol = "↑", digraph = "-!", name = "UPWARDS ARROW" },
	{ symbol = "→", digraph = "->", name = "RIGHTWARDS ARROW" },
	{ symbol = "↓", digraph = "-v", name = "DOWNWARDS ARROW" },
	{ symbol = "↔", digraph = "<>", name = "LEFT RIGHT ARROW" },
	{ symbol = "↕", digraph = "UD", name = "UP DOWN ARROW" },
	{ symbol = "⇐", digraph = "<=", name = "LEFTWARDS DOUBLE ARROW" },
	{ symbol = "⇒", digraph = "=>", name = "RIGHTWARDS DOUBLE ARROW" },
	{ symbol = "⇔", digraph = "==", name = "LEFT RIGHT DOUBLE ARROW" },
	{ symbol = "∀", digraph = "FA", name = "FOR ALL" },
	{ symbol = "∂", digraph = "dP", name = "PARTIAL DIFFERENTIAL" },
	{ symbol = "∃", digraph = "TE", name = "THERE EXISTS" },
	{ symbol = "∅", digraph = "/0", name = "EMPTY SET" },
	{ symbol = "∆", digraph = "DE", name = "INCREMENT" },
	{ symbol = "∇", digraph = "NB", name = "NABLA" },
	{ symbol = "∈", digraph = "(-", name = "ELEMENT OF" },
	{ symbol = "∋", digraph = "-)", name = "CONTAINS AS MEMBER" },
	{ symbol = "∏", digraph = "*P", name = "N-ARY PRODUCT `" },
	{ symbol = "∑", digraph = "+Z", name = "N-ARY SUMMATION `" },
	{ symbol = "−", digraph = "-2", name = "MINUS SIGN" },
	{ symbol = "∓", digraph = "-+", name = "MINUS-OR-PLUS SIGN" },
	{ symbol = "∗", digraph = "*-", name = "ASTERISK OPERATOR" },
	{ symbol = "∘", digraph = "Ob", name = "RING OPERATOR" },
	{ symbol = "∙", digraph = "Sb", name = "BULLET OPERATOR" },
	{ symbol = "√", digraph = "RT", name = "SQUARE ROOT" },
	{ symbol = "∝", digraph = "0(", name = "PROPORTIONAL TO" },
	{ symbol = "∞", digraph = "00", name = "INFINITY" },
	{ symbol = "∟", digraph = "-L", name = "RIGHT ANGLE" },
	{ symbol = "∠", digraph = "-V", name = "ANGLE" },
	{ symbol = "∥", digraph = "PP", name = "PARALLEL TO" },
	{ symbol = "∧", digraph = "AN", name = "LOGICAL AND" },
	{ symbol = "∨", digraph = "OR", name = "LOGICAL OR" },
	{ symbol = "∩", digraph = "(U", name = "INTERSECTION" },
	{ symbol = "∪", digraph = ")U", name = "UNION" },
	{ symbol = "∫", digraph = "In", name = "INTEGRAL" },
	{ symbol = "∬", digraph = "DI", name = "DOUBLE INTEGRAL" },
	{ symbol = "∮", digraph = "Io", name = "CONTOUR INTEGRAL" },
	{ symbol = "∴", digraph = ".:", name = "THEREFORE" },
	{ symbol = "∵", digraph = ":.", name = "BECAUSE" },
	{ symbol = "∶", digraph = ":R", name = "RATIO" },
	{ symbol = "∷", digraph = "::", name = "PROPORTION" },
	{ symbol = "∼", digraph = "?1", name = "TILDE OPERATOR" },
	{ symbol = "∾", digraph = "CG", name = "INVERTED LAZY S" },
	{ symbol = "≃", digraph = "?-", name = "ASYMPTOTICALLY EQUAL TO" },
	{ symbol = "≅", digraph = "?=", name = "APPROXIMATELY EQUAL TO" },
	{ symbol = "≈", digraph = "?2", name = "ALMOST EQUAL TO" },
	{ symbol = "≌", digraph = "=?", name = "ALL EQUAL TO" },
	{ symbol = "≓", digraph = "HI", name = "IMAGE OF OR APPROXIMATELY EQUAL TO" },
	{ symbol = "≠", digraph = "!=", name = "NOT EQUAL TO" },
	{ symbol = "≡", digraph = "=3", name = "IDENTICAL TO" },
	{ symbol = "≤", digraph = "=<", name = "LESS-THAN OR EQUAL TO" },
	{ symbol = "≥", digraph = ">=", name = "GREATER-THAN OR EQUAL TO" },
	{ symbol = "≪", digraph = "<*", name = "MUCH LESS-THAN" },
	{ symbol = "≫", digraph = "*>", name = "MUCH GREATER-THAN" },
	{ symbol = "≮", digraph = "!<", name = "NOT LESS-THAN" },
	{ symbol = "≯", digraph = "!>", name = "NOT GREATER-THAN" },
	{ symbol = "⊂", digraph = "(C", name = "SUBSET OF" },
	{ symbol = "⊃", digraph = ")C", name = "SUPERSET OF" },
	{ symbol = "⊆", digraph = "(_", name = "SUBSET OF OR EQUAL TO" },
	{ symbol = "⊇", digraph = ")_", name = "SUPERSET OF OR EQUAL TO" },
	{ symbol = "⊙", digraph = "0.", name = "CIRCLED DOT OPERATOR" },
	{ symbol = "⊚", digraph = "02", name = "CIRCLED RING OPERATOR" },
	{ symbol = "⊥", digraph = "-T", name = "UP TACK" },
	{ symbol = "⋅", digraph = ".P", name = "DOT OPERATOR" },
	{ symbol = "⋮", digraph = ":3", name = "VERTICAL ELLIPSIS" },
	{ symbol = "⋯", digraph = ".3", name = "MIDLINE HORIZONTAL ELLIPSIS" },
	{ symbol = "⌂", digraph = "Eh", name = "HOUSE" },
	{ symbol = "⌈", digraph = "<7", name = "LEFT CEILING" },
	{ symbol = "⌉", digraph = ">7", name = "RIGHT CEILING" },
	{ symbol = "⌊", digraph = "7<", name = "LEFT FLOOR" },
	{ symbol = "⌋", digraph = "7>", name = "RIGHT FLOOR" },
	{ symbol = "⌐", digraph = "NI", name = "REVERSED NOT SIGN" },
	{ symbol = "⌒", digraph = "(A", name = "ARC" },
	{ symbol = "⌕", digraph = "TR", name = "TELEPHONE RECORDER" },
	{ symbol = "⌠", digraph = "Iu", name = "TOP HALF INTEGRAL" },
	{ symbol = "⌡", digraph = "Il", name = "BOTTOM HALF INTEGRAL" },
	{ symbol = "〈", digraph = "</", name = "LEFT-POINTING ANGLE BRACKET" },
	{ symbol = "〉", digraph = "/>", name = "RIGHT-POINTING ANGLE BRACKET" },
	{ symbol = "␣", digraph = "Vs", name = "OPEN BOX" },
	{ symbol = "⑀", digraph = "1h", name = "OCR HOOK" },
	{ symbol = "⑁", digraph = "3h", name = "OCR CHAIR" },
	{ symbol = "⑂", digraph = "2h", name = "OCR FORK" },
	{ symbol = "⑃", digraph = "4h", name = "OCR INVERTED FORK" },
	{ symbol = "⑆", digraph = "1j", name = "OCR BRANCH BANK IDENTIFICATION" },
	{ symbol = "⑇", digraph = "2j", name = "OCR AMOUNT OF CHECK" },
	{ symbol = "⑈", digraph = "3j", name = "OCR DASH" },
	{ symbol = "⑉", digraph = "4j", name = "OCR CUSTOMER ACCOUNT NUMBER" },
	{ symbol = "⒈", digraph = "1.", name = "DIGIT ONE FULL STOP" },
	{ symbol = "⒉", digraph = "2.", name = "DIGIT TWO FULL STOP" },
	{ symbol = "⒊", digraph = "3.", name = "DIGIT THREE FULL STOP" },
	{ symbol = "⒋", digraph = "4.", name = "DIGIT FOUR FULL STOP" },
	{ symbol = "⒌", digraph = "5.", name = "DIGIT FIVE FULL STOP" },
	{ symbol = "⒍", digraph = "6.", name = "DIGIT SIX FULL STOP" },
	{ symbol = "⒎", digraph = "7.", name = "DIGIT SEVEN FULL STOP" },
	{ symbol = "⒏", digraph = "8.", name = "DIGIT EIGHT FULL STOP" },
	{ symbol = "⒐", digraph = "9.", name = "DIGIT NINE FULL STOP" },
	{ symbol = "─", digraph = "hh", name = "BOX DRAWINGS LIGHT HORIZONTAL" },
	{ symbol = "━", digraph = "HH", name = "BOX DRAWINGS HEAVY HORIZONTAL" },
	{ symbol = "│", digraph = "vv", name = "BOX DRAWINGS LIGHT VERTICAL" },
	{ symbol = "┃", digraph = "VV", name = "BOX DRAWINGS HEAVY VERTICAL" },
	{ symbol = "┄", digraph = "3-", name = "BOX DRAWINGS LIGHT TRIPLE DASH HORIZONTAL" },
	{ symbol = "┅", digraph = "3_", name = "BOX DRAWINGS HEAVY TRIPLE DASH HORIZONTAL" },
	{ symbol = "┆", digraph = "3!", name = "BOX DRAWINGS LIGHT TRIPLE DASH VERTICAL" },
	{ symbol = "┇", digraph = "3/", name = "BOX DRAWINGS HEAVY TRIPLE DASH VERTICAL" },
	{ symbol = "┈", digraph = "4-", name = "BOX DRAWINGS LIGHT QUADRUPLE DASH HORIZONTAL" },
	{ symbol = "┉", digraph = "4_", name = "BOX DRAWINGS HEAVY QUADRUPLE DASH HORIZONTAL" },
	{ symbol = "┊", digraph = "4!", name = "BOX DRAWINGS LIGHT QUADRUPLE DASH VERTICAL" },
	{ symbol = "┋", digraph = "4/", name = "BOX DRAWINGS HEAVY QUADRUPLE DASH VERTICAL" },
	{ symbol = "┌", digraph = "dr", name = "BOX DRAWINGS LIGHT DOWN AND RIGHT" },
	{ symbol = "┍", digraph = "dR", name = "BOX DRAWINGS DOWN LIGHT AND RIGHT HEAVY" },
	{ symbol = "┎", digraph = "Dr", name = "BOX DRAWINGS DOWN HEAVY AND RIGHT LIGHT" },
	{ symbol = "┏", digraph = "DR", name = "BOX DRAWINGS HEAVY DOWN AND RIGHT" },
	{ symbol = "┐", digraph = "dl", name = "BOX DRAWINGS LIGHT DOWN AND LEFT" },
	{ symbol = "┑", digraph = "dL", name = "BOX DRAWINGS DOWN LIGHT AND LEFT HEAVY" },
	{ symbol = "┒", digraph = "Dl", name = "BOX DRAWINGS DOWN HEAVY AND LEFT LIGHT" },
	{ symbol = "┓", digraph = "LD", name = "BOX DRAWINGS HEAVY DOWN AND LEFT" },
	{ symbol = "└", digraph = "ur", name = "BOX DRAWINGS LIGHT UP AND RIGHT" },
	{ symbol = "┕", digraph = "uR", name = "BOX DRAWINGS UP LIGHT AND RIGHT HEAVY" },
	{ symbol = "┖", digraph = "Ur", name = "BOX DRAWINGS UP HEAVY AND RIGHT LIGHT" },
	{ symbol = "┗", digraph = "UR", name = "BOX DRAWINGS HEAVY UP AND RIGHT" },
	{ symbol = "┘", digraph = "ul", name = "BOX DRAWINGS LIGHT UP AND LEFT" },
	{ symbol = "┙", digraph = "uL", name = "BOX DRAWINGS UP LIGHT AND LEFT HEAVY" },
	{ symbol = "┚", digraph = "Ul", name = "BOX DRAWINGS UP HEAVY AND LEFT LIGHT" },
	{ symbol = "┛", digraph = "UL", name = "BOX DRAWINGS HEAVY UP AND LEFT" },
	{ symbol = "├", digraph = "vr", name = "BOX DRAWINGS LIGHT VERTICAL AND RIGHT" },
	{ symbol = "┝", digraph = "vR", name = "BOX DRAWINGS VERTICAL LIGHT AND RIGHT HEAVY" },
	{ symbol = "┠", digraph = "Vr", name = "BOX DRAWINGS VERTICAL HEAVY AND RIGHT LIGHT" },
	{ symbol = "┣", digraph = "VR", name = "BOX DRAWINGS HEAVY VERTICAL AND RIGHT" },
	{ symbol = "┤", digraph = "vl", name = "BOX DRAWINGS LIGHT VERTICAL AND LEFT" },
	{ symbol = "┥", digraph = "vL", name = "BOX DRAWINGS VERTICAL LIGHT AND LEFT HEAVY" },
	{ symbol = "┨", digraph = "Vl", name = "BOX DRAWINGS VERTICAL HEAVY AND LEFT LIGHT" },
	{ symbol = "┫", digraph = "VL", name = "BOX DRAWINGS HEAVY VERTICAL AND LEFT" },
	{ symbol = "┬", digraph = "dh", name = "BOX DRAWINGS LIGHT DOWN AND HORIZONTAL" },
	{ symbol = "┯", digraph = "dH", name = "BOX DRAWINGS DOWN LIGHT AND HORIZONTAL HEAVY" },
	{ symbol = "┰", digraph = "Dh", name = "BOX DRAWINGS DOWN HEAVY AND HORIZONTAL LIGHT" },
	{ symbol = "┳", digraph = "DH", name = "BOX DRAWINGS HEAVY DOWN AND HORIZONTAL" },
	{ symbol = "┴", digraph = "uh", name = "BOX DRAWINGS LIGHT UP AND HORIZONTAL" },
	{ symbol = "┷", digraph = "uH", name = "BOX DRAWINGS UP LIGHT AND HORIZONTAL HEAVY" },
	{ symbol = "┸", digraph = "Uh", name = "BOX DRAWINGS UP HEAVY AND HORIZONTAL LIGHT" },
	{ symbol = "┻", digraph = "UH", name = "BOX DRAWINGS HEAVY UP AND HORIZONTAL" },
	{ symbol = "┼", digraph = "vh", name = "BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL" },
	{ symbol = "┿", digraph = "vH", name = "BOX DRAWINGS VERTICAL LIGHT AND HORIZONTAL HEAVY" },
	{ symbol = "╂", digraph = "Vh", name = "BOX DRAWINGS VERTICAL HEAVY AND HORIZONTAL LIGHT" },
	{ symbol = "╋", digraph = "VH", name = "BOX DRAWINGS HEAVY VERTICAL AND HORIZONTAL" },
	{ symbol = "╱", digraph = "FD", name = "BOX DRAWINGS LIGHT DIAGONAL UPPER RIGHT TO LOWER LEFT" },
	{ symbol = "╲", digraph = "BD", name = "BOX DRAWINGS LIGHT DIAGONAL UPPER LEFT TO LOWER RIGHT" },
	{ symbol = "▀", digraph = "TB", name = "UPPER HALF BLOCK" },
	{ symbol = "▄", digraph = "LB", name = "LOWER HALF BLOCK" },
	{ symbol = "█", digraph = "FB", name = "FULL BLOCK" },
	{ symbol = "▌", digraph = "lB", name = "LEFT HALF BLOCK" },
	{ symbol = "▐", digraph = "RB", name = "RIGHT HALF BLOCK" },
	{ symbol = "░", digraph = ".S", name = "LIGHT SHADE" },
	{ symbol = "▒", digraph = ":S", name = "MEDIUM SHADE" },
	{ symbol = "▓", digraph = "?S", name = "DARK SHADE" },
	{ symbol = "■", digraph = "fS", name = "BLACK SQUARE" },
	{ symbol = "□", digraph = "OS", name = "WHITE SQUARE" },
	{ symbol = "▢", digraph = "RO", name = "WHITE SQUARE WITH ROUNDED CORNERS" },
	{ symbol = "▣", digraph = "Rr", name = "WHITE SQUARE CONTAINING BLACK SMALL SQUARE" },
	{ symbol = "▤", digraph = "RF", name = "SQUARE WITH HORIZONTAL FILL" },
	{ symbol = "▥", digraph = "RY", name = "SQUARE WITH VERTICAL FILL" },
	{ symbol = "▦", digraph = "RH", name = "SQUARE WITH ORTHOGONAL CROSSHATCH FILL" },
	{ symbol = "▧", digraph = "RZ", name = "SQUARE WITH UPPER LEFT TO LOWER RIGHT FILL" },
	{ symbol = "▨", digraph = "RK", name = "SQUARE WITH UPPER RIGHT TO LOWER LEFT FILL" },
	{ symbol = "▩", digraph = "RX", name = "SQUARE WITH DIAGONAL CROSSHATCH FILL" },
	{ symbol = "▪", digraph = "sB", name = "BLACK SMALL SQUARE" },
	{ symbol = "▬", digraph = "SR", name = "BLACK RECTANGLE" },
	{ symbol = "▭", digraph = "Or", name = "WHITE RECTANGLE" },
	{ symbol = "▲", digraph = "UT", name = "BLACK UP-POINTING TRIANGLE" },
	{ symbol = "△", digraph = "uT", name = "WHITE UP-POINTING TRIANGLE" },
	{ symbol = "▶", digraph = "PR", name = "BLACK RIGHT-POINTING TRIANGLE" },
	{ symbol = "▷", digraph = "Tr", name = "WHITE RIGHT-POINTING TRIANGLE" },
	{ symbol = "▼", digraph = "Dt", name = "BLACK DOWN-POINTING TRIANGLE" },
	{ symbol = "▽", digraph = "dT", name = "WHITE DOWN-POINTING TRIANGLE" },
	{ symbol = "◀", digraph = "PL", name = "BLACK LEFT-POINTING TRIANGLE" },
	{ symbol = "◁", digraph = "Tl", name = "WHITE LEFT-POINTING TRIANGLE" },
	{ symbol = "◆", digraph = "Db", name = "BLACK DIAMOND" },
	{ symbol = "◇", digraph = "Dw", name = "WHITE DIAMOND" },
	{ symbol = "◊", digraph = "LZ", name = "LOZENGE" },
	{ symbol = "○", digraph = "0m", name = "WHITE CIRCLE" },
	{ symbol = "◎", digraph = "0o", name = "BULLSEYE" },
	{ symbol = "●", digraph = "0M", name = "BLACK CIRCLE" },
	{ symbol = "◐", digraph = "0L", name = "CIRCLE WITH LEFT HALF BLACK" },
	{ symbol = "◑", digraph = "0R", name = "CIRCLE WITH RIGHT HALF BLACK" },
	{ symbol = "◘", digraph = "Sn", name = "INVERSE BULLET" },
	{ symbol = "◙", digraph = "Ic", name = "INVERSE WHITE CIRCLE" },
	{ symbol = "◢", digraph = "Fd", name = "BLACK LOWER RIGHT TRIANGLE" },
	{ symbol = "◣", digraph = "Bd", name = "BLACK LOWER LEFT TRIANGLE" },
	{ symbol = "★", digraph = "*2", name = "BLACK STAR" },
	{ symbol = "☆", digraph = "*1", name = "WHITE STAR" },
	{ symbol = "☜", digraph = "<H", name = "WHITE LEFT POINTING INDEX" },
	{ symbol = "☞", digraph = ">H", name = "WHITE RIGHT POINTING INDEX" },
	{ symbol = "☺", digraph = "0u", name = "WHITE SMILING FACE" },
	{ symbol = "☻", digraph = "0U", name = "BLACK SMILING FACE" },
	{ symbol = "☼", digraph = "SU", name = "WHITE SUN WITH RAYS" },
	{ symbol = "♀", digraph = "Fm", name = "FEMALE SIGN" },
	{ symbol = "♂", digraph = "Ml", name = "MALE SIGN" },
	{ symbol = "♠", digraph = "cS", name = "BLACK SPADE SUIT" },
	{ symbol = "♡", digraph = "cH", name = "WHITE HEART SUIT" },
	{ symbol = "♢", digraph = "cD", name = "WHITE DIAMOND SUIT" },
	{ symbol = "♣", digraph = "cC", name = "BLACK CLUB SUIT" },
	{ symbol = "♩", digraph = "Md", name = "QUARTER NOTE `" },
	{ symbol = "♪", digraph = "M8", name = "EIGHTH NOTE `" },
	{ symbol = "♫", digraph = "M2", name = "BEAMED EIGHTH NOTES" },
	{ symbol = "♭", digraph = "Mb", name = "MUSIC FLAT SIGN" },
	{ symbol = "♮", digraph = "Mx", name = "MUSIC NATURAL SIGN" },
	{ symbol = "♯", digraph = "MX", name = "MUSIC SHARP SIGN" },
	{ symbol = "✓", digraph = "OK", name = "CHECK MARK" },
	{ symbol = "✗", digraph = "XX", name = "BALLOT X" },
	{ symbol = "✠", digraph = "-X", name = "MALTESE CROSS" },
	{ symbol = " ", digraph = "NS", name = "NO-BREAK SPACE" },
	{ symbol = "　", digraph = "IS", name = "IDEOGRAPHIC SPACE" },
	{ symbol = "、", digraph = ",_", name = "IDEOGRAPHIC COMMA" },
	{ symbol = "。", digraph = "._", name = "IDEOGRAPHIC FULL STOP" },
	{ symbol = "〃", digraph = '+"', name = "DITTO MARK" },
	{ symbol = "〄", digraph = "+_", name = "JAPANESE INDUSTRIAL STANDARD SYMBOL" },
	{ symbol = "々", digraph = "*_", name = "IDEOGRAPHIC ITERATION MARK" },
	{ symbol = "〆", digraph = ";_", name = "IDEOGRAPHIC CLOSING MARK" },
	{ symbol = "〇", digraph = "0_", name = "IDEOGRAPHIC NUMBER ZERO" },
	{ symbol = "《", digraph = "<+", name = "LEFT DOUBLE ANGLE BRACKET" },
	{ symbol = "》", digraph = ">+", name = "RIGHT DOUBLE ANGLE BRACKET" },
	{ symbol = "「", digraph = "<'", name = "LEFT CORNER BRACKET" },
	{ symbol = "」", digraph = ">'", name = "RIGHT CORNER BRACKET" },
	{ symbol = "『", digraph = '<"', name = "LEFT WHITE CORNER BRACKET" },
	{ symbol = "』", digraph = '>"', name = "RIGHT WHITE CORNER BRACKET" },
	{ symbol = "【", digraph = '("', name = "LEFT BLACK LENTICULAR BRACKET" },
	{ symbol = "】", digraph = ')"', name = "RIGHT BLACK LENTICULAR BRACKET" },
	{ symbol = "〒", digraph = "=T", name = "POSTAL MARK" },
	{ symbol = "〓", digraph = "=_", name = "GETA MARK" },
	{ symbol = "〔", digraph = "('", name = "LEFT TORTOISE SHELL BRACKET" },
	{ symbol = "〕", digraph = ")'", name = "RIGHT TORTOISE SHELL BRACKET" },
	{ symbol = "〖", digraph = "(I", name = "LEFT WHITE LENTICULAR BRACKET" },
	{ symbol = "〗", digraph = ")I", name = "RIGHT WHITE LENTICULAR BRACKET" },
	{ symbol = "〜", digraph = "-?", name = "WAVE DASH" },
	{ symbol = "ぁ", digraph = "A5", name = "HIRAGANA LETTER SMALL A" },
	{ symbol = "あ", digraph = "a5", name = "HIRAGANA LETTER A" },
	{ symbol = "ぃ", digraph = "I5", name = "HIRAGANA LETTER SMALL I" },
	{ symbol = "い", digraph = "i5", name = "HIRAGANA LETTER I" },
	{ symbol = "ぅ", digraph = "U5", name = "HIRAGANA LETTER SMALL U" },
	{ symbol = "う", digraph = "u5", name = "HIRAGANA LETTER U" },
	{ symbol = "ぇ", digraph = "E5", name = "HIRAGANA LETTER SMALL E" },
	{ symbol = "え", digraph = "e5", name = "HIRAGANA LETTER E" },
	{ symbol = "ぉ", digraph = "O5", name = "HIRAGANA LETTER SMALL O" },
	{ symbol = "お", digraph = "o5", name = "HIRAGANA LETTER O" },
	{ symbol = "か", digraph = "ka", name = "HIRAGANA LETTER KA" },
	{ symbol = "が", digraph = "ga", name = "HIRAGANA LETTER GA" },
	{ symbol = "き", digraph = "ki", name = "HIRAGANA LETTER KI" },
	{ symbol = "ぎ", digraph = "gi", name = "HIRAGANA LETTER GI" },
	{ symbol = "く", digraph = "ku", name = "HIRAGANA LETTER KU" },
	{ symbol = "ぐ", digraph = "gu", name = "HIRAGANA LETTER GU" },
	{ symbol = "け", digraph = "ke", name = "HIRAGANA LETTER KE" },
	{ symbol = "げ", digraph = "ge", name = "HIRAGANA LETTER GE" },
	{ symbol = "こ", digraph = "ko", name = "HIRAGANA LETTER KO" },
	{ symbol = "ご", digraph = "go", name = "HIRAGANA LETTER GO" },
	{ symbol = "さ", digraph = "sa", name = "HIRAGANA LETTER SA" },
	{ symbol = "ざ", digraph = "za", name = "HIRAGANA LETTER ZA" },
	{ symbol = "し", digraph = "si", name = "HIRAGANA LETTER SI" },
	{ symbol = "じ", digraph = "zi", name = "HIRAGANA LETTER ZI" },
	{ symbol = "す", digraph = "su", name = "HIRAGANA LETTER SU" },
	{ symbol = "ず", digraph = "zu", name = "HIRAGANA LETTER ZU" },
	{ symbol = "せ", digraph = "se", name = "HIRAGANA LETTER SE" },
	{ symbol = "ぜ", digraph = "ze", name = "HIRAGANA LETTER ZE" },
	{ symbol = "そ", digraph = "so", name = "HIRAGANA LETTER SO" },
	{ symbol = "ぞ", digraph = "zo", name = "HIRAGANA LETTER ZO" },
	{ symbol = "た", digraph = "ta", name = "HIRAGANA LETTER TA" },
	{ symbol = "だ", digraph = "da", name = "HIRAGANA LETTER DA" },
	{ symbol = "ち", digraph = "ti", name = "HIRAGANA LETTER TI" },
	{ symbol = "ぢ", digraph = "di", name = "HIRAGANA LETTER DI" },
	{ symbol = "っ", digraph = "tU", name = "HIRAGANA LETTER SMALL TU" },
	{ symbol = "つ", digraph = "tu", name = "HIRAGANA LETTER TU" },
	{ symbol = "づ", digraph = "du", name = "HIRAGANA LETTER DU" },
	{ symbol = "て", digraph = "te", name = "HIRAGANA LETTER TE" },
	{ symbol = "で", digraph = "de", name = "HIRAGANA LETTER DE" },
	{ symbol = "と", digraph = "to", name = "HIRAGANA LETTER TO" },
	{ symbol = "ど", digraph = "do", name = "HIRAGANA LETTER DO" },
	{ symbol = "な", digraph = "na", name = "HIRAGANA LETTER NA" },
	{ symbol = "に", digraph = "ni", name = "HIRAGANA LETTER NI" },
	{ symbol = "ぬ", digraph = "nu", name = "HIRAGANA LETTER NU" },
	{ symbol = "ね", digraph = "ne", name = "HIRAGANA LETTER NE" },
	{ symbol = "の", digraph = "no", name = "HIRAGANA LETTER NO" },
	{ symbol = "は", digraph = "ha", name = "HIRAGANA LETTER HA" },
	{ symbol = "ば", digraph = "ba", name = "HIRAGANA LETTER BA" },
	{ symbol = "ぱ", digraph = "pa", name = "HIRAGANA LETTER PA" },
	{ symbol = "ひ", digraph = "hi", name = "HIRAGANA LETTER HI" },
	{ symbol = "び", digraph = "bi", name = "HIRAGANA LETTER BI" },
	{ symbol = "ぴ", digraph = "pi", name = "HIRAGANA LETTER PI" },
	{ symbol = "ふ", digraph = "hu", name = "HIRAGANA LETTER HU" },
	{ symbol = "ぶ", digraph = "bu", name = "HIRAGANA LETTER BU" },
	{ symbol = "ぷ", digraph = "pu", name = "HIRAGANA LETTER PU" },
	{ symbol = "へ", digraph = "he", name = "HIRAGANA LETTER HE" },
	{ symbol = "べ", digraph = "be", name = "HIRAGANA LETTER BE" },
	{ symbol = "ぺ", digraph = "pe", name = "HIRAGANA LETTER PE" },
	{ symbol = "ほ", digraph = "ho", name = "HIRAGANA LETTER HO" },
	{ symbol = "ぼ", digraph = "bo", name = "HIRAGANA LETTER BO" },
	{ symbol = "ぽ", digraph = "po", name = "HIRAGANA LETTER PO" },
	{ symbol = "ま", digraph = "ma", name = "HIRAGANA LETTER MA" },
	{ symbol = "み", digraph = "mi", name = "HIRAGANA LETTER MI" },
	{ symbol = "む", digraph = "mu", name = "HIRAGANA LETTER MU" },
	{ symbol = "め", digraph = "me", name = "HIRAGANA LETTER ME" },
	{ symbol = "も", digraph = "mo", name = "HIRAGANA LETTER MO" },
	{ symbol = "ゃ", digraph = "yA", name = "HIRAGANA LETTER SMALL YA" },
	{ symbol = "や", digraph = "ya", name = "HIRAGANA LETTER YA" },
	{ symbol = "ゅ", digraph = "yU", name = "HIRAGANA LETTER SMALL YU" },
	{ symbol = "ゆ", digraph = "yu", name = "HIRAGANA LETTER YU" },
	{ symbol = "ょ", digraph = "yO", name = "HIRAGANA LETTER SMALL YO" },
	{ symbol = "よ", digraph = "yo", name = "HIRAGANA LETTER YO" },
	{ symbol = "ら", digraph = "ra", name = "HIRAGANA LETTER RA" },
	{ symbol = "り", digraph = "ri", name = "HIRAGANA LETTER RI" },
	{ symbol = "る", digraph = "ru", name = "HIRAGANA LETTER RU" },
	{ symbol = "れ", digraph = "re", name = "HIRAGANA LETTER RE" },
	{ symbol = "ろ", digraph = "ro", name = "HIRAGANA LETTER RO" },
	{ symbol = "ゎ", digraph = "wA", name = "HIRAGANA LETTER SMALL WA" },
	{ symbol = "わ", digraph = "wa", name = "HIRAGANA LETTER WA" },
	{ symbol = "ゐ", digraph = "wi", name = "HIRAGANA LETTER WI" },
	{ symbol = "ゑ", digraph = "we", name = "HIRAGANA LETTER WE" },
	{ symbol = "を", digraph = "wo", name = "HIRAGANA LETTER WO" },
	{ symbol = "ん", digraph = "n5", name = "HIRAGANA LETTER N `" },
	{ symbol = "ゔ", digraph = "vu", name = "HIRAGANA LETTER VU" },
	{ symbol = "゛", digraph = '"5', name = "KATAKANA-HIRAGANA VOICED SOUND MARK" },
	{ symbol = "゜", digraph = "05", name = "KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK" },
	{ symbol = "ゝ", digraph = "*5", name = "HIRAGANA ITERATION MARK" },
	{ symbol = "ゞ", digraph = "+5", name = "HIRAGANA VOICED ITERATION MARK" },
	{ symbol = "ァ", digraph = "a6", name = "KATAKANA LETTER SMALL A" },
	{ symbol = "ア", digraph = "A6", name = "KATAKANA LETTER A" },
	{ symbol = "ィ", digraph = "i6", name = "KATAKANA LETTER SMALL I" },
	{ symbol = "イ", digraph = "I6", name = "KATAKANA LETTER I" },
	{ symbol = "ゥ", digraph = "u6", name = "KATAKANA LETTER SMALL U" },
	{ symbol = "ウ", digraph = "U6", name = "KATAKANA LETTER U" },
	{ symbol = "ェ", digraph = "e6", name = "KATAKANA LETTER SMALL E" },
	{ symbol = "エ", digraph = "E6", name = "KATAKANA LETTER E" },
	{ symbol = "ォ", digraph = "o6", name = "KATAKANA LETTER SMALL O" },
	{ symbol = "オ", digraph = "O6", name = "KATAKANA LETTER O" },
	{ symbol = "カ", digraph = "Ka", name = "KATAKANA LETTER KA" },
	{ symbol = "ガ", digraph = "Ga", name = "KATAKANA LETTER GA" },
	{ symbol = "キ", digraph = "Ki", name = "KATAKANA LETTER KI" },
	{ symbol = "ギ", digraph = "Gi", name = "KATAKANA LETTER GI" },
	{ symbol = "ク", digraph = "Ku", name = "KATAKANA LETTER KU" },
	{ symbol = "グ", digraph = "Gu", name = "KATAKANA LETTER GU" },
	{ symbol = "ケ", digraph = "Ke", name = "KATAKANA LETTER KE" },
	{ symbol = "ゲ", digraph = "Ge", name = "KATAKANA LETTER GE" },
	{ symbol = "コ", digraph = "Ko", name = "KATAKANA LETTER KO" },
	{ symbol = "ゴ", digraph = "Go", name = "KATAKANA LETTER GO" },
	{ symbol = "サ", digraph = "Sa", name = "KATAKANA LETTER SA" },
	{ symbol = "ザ", digraph = "Za", name = "KATAKANA LETTER ZA" },
	{ symbol = "シ", digraph = "Si", name = "KATAKANA LETTER SI" },
	{ symbol = "ジ", digraph = "Zi", name = "KATAKANA LETTER ZI" },
	{ symbol = "ス", digraph = "Su", name = "KATAKANA LETTER SU" },
	{ symbol = "ズ", digraph = "Zu", name = "KATAKANA LETTER ZU" },
	{ symbol = "セ", digraph = "Se", name = "KATAKANA LETTER SE" },
	{ symbol = "ゼ", digraph = "Ze", name = "KATAKANA LETTER ZE" },
	{ symbol = "ソ", digraph = "So", name = "KATAKANA LETTER SO" },
	{ symbol = "ゾ", digraph = "Zo", name = "KATAKANA LETTER ZO" },
	{ symbol = "タ", digraph = "Ta", name = "KATAKANA LETTER TA" },
	{ symbol = "ダ", digraph = "Da", name = "KATAKANA LETTER DA" },
	{ symbol = "チ", digraph = "Ti", name = "KATAKANA LETTER TI" },
	{ symbol = "ヂ", digraph = "Di", name = "KATAKANA LETTER DI" },
	{ symbol = "ッ", digraph = "TU", name = "KATAKANA LETTER SMALL TU" },
	{ symbol = "ツ", digraph = "Tu", name = "KATAKANA LETTER TU" },
	{ symbol = "ヅ", digraph = "Du", name = "KATAKANA LETTER DU" },
	{ symbol = "テ", digraph = "Te", name = "KATAKANA LETTER TE" },
	{ symbol = "デ", digraph = "De", name = "KATAKANA LETTER DE" },
	{ symbol = "ト", digraph = "To", name = "KATAKANA LETTER TO" },
	{ symbol = "ド", digraph = "Do", name = "KATAKANA LETTER DO" },
	{ symbol = "ナ", digraph = "Na", name = "KATAKANA LETTER NA" },
	{ symbol = "ニ", digraph = "Ni", name = "KATAKANA LETTER NI" },
	{ symbol = "ヌ", digraph = "Nu", name = "KATAKANA LETTER NU" },
	{ symbol = "ネ", digraph = "Ne", name = "KATAKANA LETTER NE" },
	{ symbol = "ノ", digraph = "No", name = "KATAKANA LETTER NO" },
	{ symbol = "ハ", digraph = "Ha", name = "KATAKANA LETTER HA" },
	{ symbol = "バ", digraph = "Ba", name = "KATAKANA LETTER BA" },
	{ symbol = "パ", digraph = "Pa", name = "KATAKANA LETTER PA" },
	{ symbol = "ヒ", digraph = "Hi", name = "KATAKANA LETTER HI" },
	{ symbol = "ビ", digraph = "Bi", name = "KATAKANA LETTER BI" },
	{ symbol = "ピ", digraph = "Pi", name = "KATAKANA LETTER PI" },
	{ symbol = "フ", digraph = "Hu", name = "KATAKANA LETTER HU" },
	{ symbol = "ブ", digraph = "Bu", name = "KATAKANA LETTER BU" },
	{ symbol = "プ", digraph = "Pu", name = "KATAKANA LETTER PU" },
	{ symbol = "ヘ", digraph = "He", name = "KATAKANA LETTER HE" },
	{ symbol = "ベ", digraph = "Be", name = "KATAKANA LETTER BE" },
	{ symbol = "ペ", digraph = "Pe", name = "KATAKANA LETTER PE" },
	{ symbol = "ホ", digraph = "Ho", name = "KATAKANA LETTER HO" },
	{ symbol = "ボ", digraph = "Bo", name = "KATAKANA LETTER BO" },
	{ symbol = "ポ", digraph = "Po", name = "KATAKANA LETTER PO" },
	{ symbol = "マ", digraph = "Ma", name = "KATAKANA LETTER MA" },
	{ symbol = "ミ", digraph = "Mi", name = "KATAKANA LETTER MI" },
	{ symbol = "ム", digraph = "Mu", name = "KATAKANA LETTER MU" },
	{ symbol = "メ", digraph = "Me", name = "KATAKANA LETTER ME" },
	{ symbol = "モ", digraph = "Mo", name = "KATAKANA LETTER MO" },
	{ symbol = "ャ", digraph = "YA", name = "KATAKANA LETTER SMALL YA" },
	{ symbol = "ヤ", digraph = "Ya", name = "KATAKANA LETTER YA" },
	{ symbol = "ュ", digraph = "YU", name = "KATAKANA LETTER SMALL YU" },
	{ symbol = "ユ", digraph = "Yu", name = "KATAKANA LETTER YU" },
	{ symbol = "ョ", digraph = "YO", name = "KATAKANA LETTER SMALL YO" },
	{ symbol = "ヨ", digraph = "Yo", name = "KATAKANA LETTER YO" },
	{ symbol = "ラ", digraph = "Ra", name = "KATAKANA LETTER RA" },
	{ symbol = "リ", digraph = "Ri", name = "KATAKANA LETTER RI" },
	{ symbol = "ル", digraph = "Ru", name = "KATAKANA LETTER RU" },
	{ symbol = "レ", digraph = "Re", name = "KATAKANA LETTER RE" },
	{ symbol = "ロ", digraph = "Ro", name = "KATAKANA LETTER RO" },
	{ symbol = "ヮ", digraph = "WA", name = "KATAKANA LETTER SMALL WA" },
	{ symbol = "ワ", digraph = "Wa", name = "KATAKANA LETTER WA" },
	{ symbol = "ヰ", digraph = "Wi", name = "KATAKANA LETTER WI" },
	{ symbol = "ヱ", digraph = "We", name = "KATAKANA LETTER WE" },
	{ symbol = "ヲ", digraph = "Wo", name = "KATAKANA LETTER WO" },
	{ symbol = "ン", digraph = "N6", name = "KATAKANA LETTER N `" },
	{ symbol = "ヴ", digraph = "Vu", name = "KATAKANA LETTER VU" },
	{ symbol = "ヵ", digraph = "KA", name = "KATAKANA LETTER SMALL KA" },
	{ symbol = "ヶ", digraph = "KE", name = "KATAKANA LETTER SMALL KE" },
	{ symbol = "ヷ", digraph = "Va", name = "KATAKANA LETTER VA" },
	{ symbol = "ヸ", digraph = "Vi", name = "KATAKANA LETTER VI" },
	{ symbol = "ヹ", digraph = "Ve", name = "KATAKANA LETTER VE" },
	{ symbol = "ヺ", digraph = "Vo", name = "KATAKANA LETTER VO" },
	{ symbol = "・", digraph = ".6", name = "KATAKANA MIDDLE DOT" },
	{ symbol = "ー", digraph = "-6", name = "KATAKANA-HIRAGANA PROLONGED SOUND MARK" },
	{ symbol = "ヽ", digraph = "*6", name = "KATAKANA ITERATION MARK" },
	{ symbol = "ヾ", digraph = "+6", name = "KATAKANA VOICED ITERATION MARK" },
	{ symbol = "ㄅ", digraph = "b4", name = "BOPOMOFO LETTER B" },
	{ symbol = "ㄆ", digraph = "p4", name = "BOPOMOFO LETTER P" },
	{ symbol = "ㄇ", digraph = "m4", name = "BOPOMOFO LETTER M" },
	{ symbol = "ㄈ", digraph = "f4", name = "BOPOMOFO LETTER F" },
	{ symbol = "ㄉ", digraph = "d4", name = "BOPOMOFO LETTER D" },
	{ symbol = "ㄊ", digraph = "t4", name = "BOPOMOFO LETTER T" },
	{ symbol = "ㄋ", digraph = "n4", name = "BOPOMOFO LETTER N `" },
	{ symbol = "ㄌ", digraph = "l4", name = "BOPOMOFO LETTER L" },
	{ symbol = "ㄍ", digraph = "g4", name = "BOPOMOFO LETTER G" },
	{ symbol = "ㄎ", digraph = "k4", name = "BOPOMOFO LETTER K" },
	{ symbol = "ㄏ", digraph = "h4", name = "BOPOMOFO LETTER H" },
	{ symbol = "ㄐ", digraph = "j4", name = "BOPOMOFO LETTER J" },
	{ symbol = "ㄑ", digraph = "q4", name = "BOPOMOFO LETTER Q" },
	{ symbol = "ㄒ", digraph = "x4", name = "BOPOMOFO LETTER X" },
	{ symbol = "ㄓ", digraph = "zh", name = "BOPOMOFO LETTER ZH" },
	{ symbol = "ㄔ", digraph = "ch", name = "BOPOMOFO LETTER CH" },
	{ symbol = "ㄕ", digraph = "sh", name = "BOPOMOFO LETTER SH" },
	{ symbol = "ㄖ", digraph = "r4", name = "BOPOMOFO LETTER R" },
	{ symbol = "ㄗ", digraph = "z4", name = "BOPOMOFO LETTER Z" },
	{ symbol = "ㄘ", digraph = "c4", name = "BOPOMOFO LETTER C" },
	{ symbol = "ㄙ", digraph = "s4", name = "BOPOMOFO LETTER S" },
	{ symbol = "ㄚ", digraph = "a4", name = "BOPOMOFO LETTER A" },
	{ symbol = "ㄛ", digraph = "o4", name = "BOPOMOFO LETTER O" },
	{ symbol = "ㄜ", digraph = "e4", name = "BOPOMOFO LETTER E" },
	{ symbol = "ㄞ", digraph = "ai", name = "BOPOMOFO LETTER AI" },
	{ symbol = "ㄟ", digraph = "ei", name = "BOPOMOFO LETTER EI" },
	{ symbol = "ㄠ", digraph = "au", name = "BOPOMOFO LETTER AU" },
	{ symbol = "ㄡ", digraph = "ou", name = "BOPOMOFO LETTER OU" },
	{ symbol = "ㄢ", digraph = "an", name = "BOPOMOFO LETTER AN" },
	{ symbol = "ㄣ", digraph = "en", name = "BOPOMOFO LETTER EN" },
	{ symbol = "ㄤ", digraph = "aN", name = "BOPOMOFO LETTER ANG" },
	{ symbol = "ㄥ", digraph = "eN", name = "BOPOMOFO LETTER ENG" },
	{ symbol = "ㄦ", digraph = "er", name = "BOPOMOFO LETTER ER" },
	{ symbol = "ㄧ", digraph = "i4", name = "BOPOMOFO LETTER I" },
	{ symbol = "ㄨ", digraph = "u4", name = "BOPOMOFO LETTER U" },
	{ symbol = "ㄩ", digraph = "iu", name = "BOPOMOFO LETTER IU" },
	{ symbol = "ㄪ", digraph = "v4", name = "BOPOMOFO LETTER V" },
	{ symbol = "ㄫ", digraph = "nG", name = "BOPOMOFO LETTER NG" },
	{ symbol = "ㄬ", digraph = "gn", name = "BOPOMOFO LETTER GN" },
	{ symbol = "㈠", digraph = "1c", name = "PARENTHESIZED IDEOGRAPH ONE" },
	{ symbol = "㈡", digraph = "2c", name = "PARENTHESIZED IDEOGRAPH TWO" },
	{ symbol = "㈢", digraph = "3c", name = "PARENTHESIZED IDEOGRAPH THREE" },
	{ symbol = "㈣", digraph = "4c", name = "PARENTHESIZED IDEOGRAPH FOUR" },
	{ symbol = "㈤", digraph = "5c", name = "PARENTHESIZED IDEOGRAPH FIVE" },
	{ symbol = "㈥", digraph = "6c", name = "PARENTHESIZED IDEOGRAPH SIX" },
	{ symbol = "㈦", digraph = "7c", name = "PARENTHESIZED IDEOGRAPH SEVEN" },
	{ symbol = "㈧", digraph = "8c", name = "PARENTHESIZED IDEOGRAPH EIGHT" },
	{ symbol = "㈨", digraph = "9c", name = "PARENTHESIZED IDEOGRAPH NINE" },
	{ symbol = "ﬀ", digraph = "ff", name = "LATIN SMALL LIGATURE FF" },
	{ symbol = "ﬁ", digraph = "fi", name = "LATIN SMALL LIGATURE FI" },
	{ symbol = "ﬂ", digraph = "fl", name = "LATIN SMALL LIGATURE FL" },
	{ symbol = "ﬅ", digraph = "ft", name = "LATIN SMALL LIGATURE LONG S T" },
	{ symbol = "ﬆ", digraph = "st", name = "LATIN SMALL LIGATURE ST" },
}
