return {
	kind_icons = {
		Array = "󰅨", -- nf-md-code_brackets
		Boolean = "", -- nf-md-checkbox_marked_circle_outline
		Class = "", -- nf-md-language_cpp
		Color = "", -- nf-md-palette
		Control = "󰭩", -- nf-md-cog
		Collapsed = "󰁄", -- nf-md-chevron_right
		Constant = "", -- nf-md-sigma
		Constructor = "", -- nf-md-hammer_wrench
		Supermaven = "󱜙", -- nf-md-robot
		Enum = "󰆙", -- nf-md-numeric
		EnumMember = "", -- nf-md-numeric
		Event = "󰂚 ", -- nf-md-calendar_alert
		Field = "", -- nf-md-variable
		File = "󰈙 ", -- nf-md-file
		Folder = "󰉋 ", -- nf-md-folder
		Function = "󰡱", -- nf-md-function
		Interface = "󰌨", -- nf-md-application_braces
		Key = "󰌋", -- nf-md-key
		Keyword = "󰌆 ", -- nf-md-code_tags
		Method = "󰆧", -- nf-md-hammer_wrench
		Module = "󰏗", -- nf-md-package
		Namespace = "󰅩", -- nf-md-code_braces
		Null = "󰟢", -- nf-md-circle_off_outline
		Number = "󰎠", -- nf-md-numeric
		Object = "", -- nf-md-code_braces
		Operator = "", -- nf-md-plus_minus
		Package = "󰏗", -- nf-md-package
		Property = "󰜢", -- nf-md-text_box
		Reference = "󰈇", -- nf-md-link
		Snippet = "", -- nf-md-text_box_multiple
		String = "", -- nf-md-text
		Struct = "", -- nf-md-structure
		TabNine = "󰏚 ", -- nf-md-robot_industrial
		Text = "󰊄", -- nf-md-text
		TypeParameter = "󰗄 ", -- nf-md-format_letter_case
		Unit = "󰑭 ", -- nf-md-ruler
		Value = "󰎠 ", -- nf-md-numeric
		Variable = "󰫧", -- nf-md-variable
	},
	git = {
		LineAdded = " ", -- nf-md-plus
		LineModified = " ", -- nf-md-pencil
		LineRemoved = " ", -- nf-md-close
		FileDeleted = "󰆴 ", -- nf-md-close
		FileIgnored = " ", -- nf-md-eye_off
		FileRenamed = "󰑕 ", -- nf-md-rename_box
		FileStaged = " ", -- nf-md-check
		FileUnmerged = "󰧧 ", -- nf-md-source_merge
		FileUnstaged = "󰄨 ", -- nf-md-alert_circle
		FileUntracked = "󰐕 ", -- nf-md-plus
		Diff = "󰡀 ", -- nf-md-file_compare
		Repo = "󰧧 ", -- nf-md-source_repository
		Octoface = "󰊤 ", -- nf-md-github
		Branch = "󰘬 ", -- nf-md-source_branch
	},
	misc = {
		Robot = "󰚩 ", -- nf-md-robot
		Squirrel = "󰚩 ", -- nf-md-robot (alternative: 󰚩)
		Tag = "󰓹 ", -- nf-md-tag
		Watch = "󰥔 ", -- nf-md-watch
		Smiley = "󰗖 ", -- nf-md-emoticon
		Package = "󰏗 ", -- nf-md-package
		CircuitBoard = "󰘓 ", -- nf-md-chip
		Unix = "󰌽 ", -- nf-md-tux
		Dos = "󰖳 ", -- nf-md-windows
		Mac = "󰀵 ", -- nf-md-apple
		dots = "󰇘 ", -- nf-md-dots_horizontal
	},

	diagnostics = {
		Error = "󰅙 ", -- nf-md-alert_circle
		Warn = "󰀪 ", -- nf-md-alert
		Hint = "󰌵 ", -- nf-md-lightbulb
		Info = "󰋼 ", -- nf-md-information
	},
	ui = {
		ArrowCircleDown = "󰁃 ", -- nf-md-chevron_down
		ArrowCircleLeft = "󰁈 ", -- nf-md-chevron_left
		ArrowCircleRight = "󰁅 ", -- nf-md-chevron_right
		ArrowCircleUp = "󰁁 ", -- nf-md-chevron_up
		BoldArrowDown = "󰁃 ", -- nf-md-chevron_down
		BoldArrowLeft = "󰁈 ", -- nf-md-chevron_left
		BoldArrowRight = "󰁅 ", -- nf-md-chevron_right
		BoldArrowUp = "󰁁 ", -- nf-md-chevron_up
		BoldClose = "󰅖 ", -- nf-md-close
		BoldDividerLeft = "󰁈 ", -- nf-md-chevron_left
		BoldDividerRight = "󰁅 ", -- nf-md-chevron_right
		BoldLineLeft = "󰁈 ", -- nf-md-chevron_left
		BookMark = "󰂺 ", -- nf-md-bookmark
		BoxChecked = "󰄬 ", -- nf-md-check
		Bug = "󰆽 ", -- nf-md-bug
		Stacks = "󰏗 ", -- nf-md-package
		Scopes = "󰀫 ", -- nf-md-variable
		Watches = "󰥔 ", -- nf-md-watch
		DebugConsole = "󰞷 ", -- nf-md-console
		Calendar = "󰃭 ", -- nf-md-calendar
		Check = "󰄬 ", -- nf-md-check
		ChevronRight = "󰁅 ", -- nf-md-chevron_right
		ChevronShortDown = "󰁃 ", -- nf-md-chevron_down
		ChevronShortLeft = "󰁈 ", -- nf-md-chevron_left
		ChevronShortRight = "󰁅 ", -- nf-md-chevron_right
		ChevronShortUp = "󰁁 ", -- nf-md-chevron_up
		Circle = "󰝤 ", -- nf-md-circle
		Close = "󰅖 ", -- nf-md-close
		CloudDownload = "󰇚 ", -- nf-md-cloud_download
		Code = "󰞶 ", -- nf-md-code
		Comment = "󰅺 ", -- nf-md-comment
		Dashboard = "󰋊 ", -- nf-md-view_dashboard
		DividerLeft = "󰁈 ", -- nf-md-chevron_left
		DividerRight = "󰁅 ", -- nf-md-chevron_right
		DoubleChevronRight = "󰁅󰁅 ", -- nf-md-chevron_right (double)
		Ellipsis = "󰇘 ", -- nf-md-dots_horizontal
		EmptyFolder = "󰉋 ", -- nf-md-folder
		EmptyFolderOpen = "󰉋 ", -- nf-md-folder_open
		File = "󰈙 ", -- nf-md-file
		FileSymlink = "󰉒 ", -- nf-md-file_link
		Files = "󰈙 ", -- nf-md-file_multiple
		FindFile = "󰈞 ", -- nf-md-file_find
		FindText = "󰊄 ", -- nf-md-text_search
		Fire = "󰐍 ", -- nf-md-fire
		Folder = "󰉋 ", -- nf-md-folder
		FolderOpen = "󰉋 ", -- nf-md-folder_open
		FolderSymlink = "󰉒 ", -- nf-md-folder_link
		Forward = "󰁅 ", -- nf-md-chevron_right
		Gear = "󰣏 ", -- nf-md-cog
		History = "󰋚 ", -- nf-md-history
		Lightbulb = "󰌵 ", -- nf-md-lightbulb
		LineLeft = "󰁈 ", -- nf-md-chevron_left
		LineMiddle = "󰁈 ", -- nf-md-chevron_left
		List = "󰏒 ", -- nf-md-format_list_bulleted
		Lock = "󰌾 ", -- nf-md-lock
		NewFile = "󰈙 ", -- nf-md-file_plus
		Note = "󱎚 ", -- nf-md-note
		Package = "󰏗 ", -- nf-md-package
		Pencil = "󰏫 ", -- nf-md-pencil
		Plus = "󰐕 ", -- nf-md-plus
		Project = "󰏗 ", -- nf-md-package
		Search = "󰍉 ", -- nf-md-magnify
		SignIn = "󰈼 ", -- nf-md-login
		SignOut = "󰈽 ", -- nf-md-logout
		Tab = "󰌒 ", -- nf-md-tab
		Table = "󰓯 ", -- nf-md-table
		Target = "󰀫 ", -- nf-md-target
		Telescope = "󰭎 ", -- nf-md-telescope
		Text = "󰉾 ", -- nf-md-text
		Tree = "󰉋 ", -- nf-md-folder_tree
		Triangle = "󰐊 ", -- nf-md-triangle
		TriangleShortArrowDown = "󰁃 ", -- nf-md-chevron_down
		TriangleShortArrowLeft = "󰁈 ", -- nf-md-chevron_left
		TriangleShortArrowRight = "󰁅 ", -- nf-md-chevron_right
		TriangleShortArrowUp = "󰁁 ", -- nf-md-chevron_up
	},
}
