return {
	-- {
	--   'nvim-orgmode/orgmode',
	--   dependencies = {
	--     'nvim-telescope/telescope.nvim',
	--     'nvim-orgmode/telescope-orgmode.nvim',
	--     'nvim-orgmode/org-bullets.nvim',
	--     "chipsenkbeil/org-roam.nvim",
	--   },
	--   event = 'VeryLazy',
	--   ft = "org",
	--   config = function()
	--     require('orgmode').setup({
	--       org_agenda_files = '~/orgfiles/**/*',
	--       org_default_notes_file = '~/orgfiles/refile.org',
	--     })
	--     require('org-bullets').setup({
	--       concealcursor = false, -- If false then when the cursor is on a line underlying characters are visible
	--       symbols = {
	--         -- list symbol
	--         list = "•",
	--         -- headlines can be a list
	--         -- headlines = { "◉", "○", "✸", "✿" },
	--         -- -- or a function that receives the defaults and returns a list
	--         -- headlines = function(default_list)
	--         --   table.insert(default_list, "♥")
	--         --   return default_list
	--         -- end,
	--         -- or false to disable the symbol. Works for all symbols
	--         -- or a table of tables that provide a name
	--         -- and (optional) highlight group for each headline level
	--         headlines = {
	--           { "◉", "Title" },
	--           { "○", "String" },
	--           { "✸", "Comment" },
	--           { "✿", "Special" },
	--         },
	--         checkboxes = {
	--           half = { "", "@org.checkbox.halfchecked" },
	--           done = { "✓", "@org.keyword.done" },
	--           todo = { "˟", "@org.keyword.todo" },
	--         },
	--       }
	--     })
	--     require("org-roam").setup({
	--       directory = "~/orgfiles"
	--     })
	--
	--     -- Experimental LSP support
	--     vim.lsp.enable('org')
	--   end,
	-- }
}
